import { StyleSheet } from 'react-native';
import type { AppTheme } from '../hooks/use-app-theme';

export function createChoiceOptionStyles(theme: AppTheme) {
  const { colors, type, radii, spacing, touchTarget, shadows } = theme;
  return StyleSheet.create({
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: spacing.md,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      marginBottom: spacing.sm,
      minHeight: touchTarget.min,
      gap: spacing.md,
      ...shadows.card,
    },
    filled: { backgroundColor: colors.primary, ...shadows.button },
    correct: { backgroundColor: colors.successBg, borderWidth: 2, borderColor: colors.success },
    wrong: { backgroundColor: colors.errorBg, borderWidth: 2, borderColor: colors.error },
    disabled: { opacity: 0.95 },
    badge: {
      width: 36,
      height: 36,
      borderRadius: radii.sm,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    badgeFilled: { backgroundColor: 'rgba(255,255,255,0.18)' },
    badgeCorrect: { backgroundColor: colors.success },
    letter: { ...type.label, fontSize: 14, color: colors.textMuted },
    letterLight: { color: '#fff' },
    text: { ...type.label, fontSize: 15, flex: 1, letterSpacing: -0.1 },
    textFilled: { color: '#fff' },
    textCorrect: { color: colors.text },
    checkWrap: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    eliminatedBadge: {
      backgroundColor: colors.border,
      borderColor: colors.textLight,
    },
    eliminatedLetter: { color: colors.textLight },
    eliminatedText: { textDecorationLine: 'line-through', color: colors.textLight },
  });
}

export function createPrimaryButtonStyles(theme: AppTheme) {
  const { colors, type, radii, spacing, shadows } = theme;
  return StyleSheet.create({
    base: {
      paddingVertical: 0,
      paddingHorizontal: spacing.lg,
      borderRadius: radii.lg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'transparent',
    },
    inner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
    primary: { backgroundColor: colors.primary, ...shadows.button },
    accent: { backgroundColor: colors.accent, ...shadows.soft },
    outline: {
      backgroundColor: theme.isDark ? 'rgba(59,130,255,0.12)' : colors.primaryMuted,
      borderColor: colors.primary,
    },
    white: { backgroundColor: colors.surface },
    ghost: { backgroundColor: 'transparent', borderColor: colors.border },
    success: { backgroundColor: colors.success },
    pressed: { opacity: 0.92, transform: [{ scale: 0.98 }] },
    pressedReducedMotion: { opacity: 0.88 },
    disabled: { opacity: 0.5 },
    text: { ...type.label, color: '#fff' },
    textLg: { fontSize: 16 },
    textAccent: { ...type.label, color: colors.text },
    textOutline: { ...type.label, color: colors.primary },
    textWhite: { ...type.label, color: colors.primary },
    iconLeft: { marginRight: spacing.sm },
    iconRight: { marginLeft: spacing.sm },
  });
}

export function createEmptyStateStyles(theme: AppTheme) {
  const { colors, spacing, type, radii } = theme;
  return StyleSheet.create({
    wrap: { alignItems: 'center', paddingVertical: spacing.xxl, paddingHorizontal: spacing.lg },
    iconWrap: {
      width: 84,
      height: 84,
      borderRadius: radii.xl,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing.lg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    title: { ...type.title, textAlign: 'center' },
    description: { ...type.bodyMuted, textAlign: 'center', marginTop: spacing.sm, maxWidth: 300 },
    btn: { marginTop: spacing.lg, alignSelf: 'stretch', width: '100%' },
  });
}

export function createPillStyles(theme: AppTheme) {
  const { type, radii } = theme;
  return StyleSheet.create({
    pill: {
      alignSelf: 'flex-start',
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: radii.sm,
    },
    text: {
      fontFamily: type.label.fontFamily,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
  });
}

export function createSettingsStyles(theme: AppTheme) {
  const { colors, type, spacing, radii } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.md,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backBtn: { width: 28, height: 28, justifyContent: 'center' },
    headerTitle: { fontFamily: type.headline.fontFamily, fontSize: 17, color: colors.text, letterSpacing: -0.3 },
    body: { padding: spacing.md },
    userCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    userAvatar: {
      width: 50,
      height: 50,
      borderRadius: radii.lg,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    userInitial: { fontFamily: type.display.fontFamily, fontSize: 18, color: colors.primaryDark },
    userName: { ...type.label, fontSize: 15 },
    userEmail: { ...type.caption, textTransform: 'none', marginTop: 1 },
    premiumCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      borderRadius: radii.xl,
      padding: spacing.md,
      marginBottom: spacing.lg,
    },
    premiumIcon: {
      width: 44,
      height: 44,
      borderRadius: radii.md,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    premiumTitle: { fontFamily: type.label.fontFamily, fontSize: 14, color: '#fff' },
    premiumSub: { fontFamily: type.bodyMedium.fontFamily, fontSize: 11, color: 'rgba(255,255,255,0.7)', marginTop: 2 },
    entitlementNote: { ...type.caption, textTransform: 'none', marginBottom: spacing.lg, paddingHorizontal: spacing.sm },
    sectionLbl: {
      ...type.caption,
      paddingHorizontal: spacing.sm,
      marginBottom: spacing.sm,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    group: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      overflow: 'hidden',
      marginBottom: spacing.lg,
    },
    row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md },
    rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
    rowIcon: {
      width: 36,
      height: 36,
      borderRadius: radii.sm,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowText: { flex: 1 },
    rowLabel: { ...type.label, fontSize: 14 },
    rowSub: { ...type.caption, textTransform: 'none', marginTop: 2 },
    rowValue: { ...type.subtitle, marginRight: 4 },
    disclaimerBox: {
      flexDirection: 'row',
      gap: spacing.sm,
      backgroundColor: colors.warnBg,
      borderRadius: radii.lg,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.warnBorder,
    },
    disclaimer: {
      ...type.caption,
      flex: 1,
      lineHeight: 16,
      color: colors.disclaimerText,
      textTransform: 'none',
    },
    footer: { textAlign: 'center', ...type.caption, marginTop: spacing.lg, textTransform: 'none' },
  });
}

export function createTabLayoutStyles(theme: AppTheme) {
  const { colors, fonts, radii } = theme;
  return StyleSheet.create({
    tabItem: { paddingTop: 4, paddingBottom: 2, minHeight: 58 },
    tabLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      letterSpacing: 0.1,
      marginTop: 4,
      includeFontPadding: false,
      textAlign: 'center',
    },
    iconWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      height: 34,
      minWidth: 50,
      paddingHorizontal: 14,
      borderRadius: radii.full,
    },
    iconWrapActive: {
      backgroundColor: colors.primaryMuted,
    },
    activeBar: {
      position: 'absolute',
      top: 3,
      width: 4,
      height: 4,
      backgroundColor: colors.primary,
      borderRadius: 2,
    },
    loading: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
    },
  });
}

export function createScreenShellStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    card: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardTitle: { fontFamily: fonts.bodyBold, fontSize: 15, color: colors.text, letterSpacing: -0.15 },
    cardMeta: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    sectionTitle: { fontFamily: fonts.bodyBold, fontSize: 17, color: colors.text, letterSpacing: -0.15 },
  });
}

export function createDashboardStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    hero: {
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.lg,
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
      overflow: 'hidden',
    },
    sparkleTop: { position: 'absolute', top: 72, left: spacing.lg },
    sparkleMid: { position: 'absolute', bottom: 48, right: spacing.xl, opacity: 0.5 },
    heroTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.md,
      marginBottom: spacing.xs,
    },
    heroGreet: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 13,
      color: 'rgba(255,255,255,0.72)',
      letterSpacing: 0.2,
      textTransform: 'none',
    },
    heroName: {
      fontFamily: fonts.display,
      fontSize: 21,
      color: '#fff',
      marginTop: 4,
      letterSpacing: -0.5,
      lineHeight: 28,
    },
    bellBtn: {
      width: 44,
      height: 44,
      borderRadius: radii.lg,
      backgroundColor: 'rgba(255,255,255,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    statRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md },
    statPill: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: 'rgba(255,255,255,0.11)',
      borderRadius: radii.lg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      minWidth: 0,
    },
    statPillReadiness: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
      backgroundColor: 'rgba(255,255,255,0.11)',
      borderRadius: radii.lg,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.xs,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    statIconWrap: {
      width: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statTextWrap: { flex: 1, minWidth: 0 },
    pctBadge: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    pctBadgeText: { fontFamily: fonts.display, fontSize: 11, color: colors.primary },
    statVal: { fontFamily: fonts.display, fontSize: 17, color: '#fff', lineHeight: 20, letterSpacing: -0.3 },
    statLbl: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: 'rgba(255,255,255,0.65)',
      marginTop: 2,
      lineHeight: 13,
    },
    statLblCenter: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: 'rgba(255,255,255,0.65)',
      textAlign: 'center',
      lineHeight: 13,
    },
    sectionPad: { paddingHorizontal: spacing.md, paddingTop: spacing.md },
    continueCard: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    continueRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.sm },
    continueIcon: {
      width: 46,
      height: 46,
      borderRadius: 16,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    continueAbbr: { fontFamily: fonts.bodyBold, color: colors.primary, fontSize: 15 },
    continueLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.textLight,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    continueTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: colors.text, marginTop: 2, letterSpacing: -0.15 },
    continueMeta: { fontFamily: fonts.bodySemiBold, fontSize: 13, color: colors.textMuted },
    pasapathCard: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    pasapathHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    pasapathLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.primary,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    pasapathMeta: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.textMuted, marginTop: 4, marginBottom: spacing.sm },
    pasapathTask: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingVertical: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    pasapathTaskTitle: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    pasapathTaskSub: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    quickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
    quickAction: {
      width: '48%',
      minHeight: 92,
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'space-between',
    },
    quickActionText: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    goalCard: {
      borderRadius: 20,
      padding: spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      marginBottom: spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(245,166,35,0.2)',
      ...shadows.card,
    },
    goalLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.accentDark,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    goalTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: colors.text, marginTop: 2, letterSpacing: -0.15 },
    goalHint: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 3 },
    sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: spacing.sm },
    sectionTitle: { fontFamily: fonts.bodyBold, fontSize: 17, color: colors.text, letterSpacing: -0.15 },
    quickRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: spacing.md,
      marginBottom: spacing.sm,
      minHeight: 88,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    quickIcon: { width: 44, height: 44, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
    quickName: { fontFamily: fonts.bodyBold, fontSize: 15, color: colors.text, letterSpacing: -0.15 },
    quickMeta: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    playBtn: { width: 36, height: 36, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
    challengeCard: { borderRadius: radii.xl, padding: spacing.lg, marginTop: spacing.md, marginBottom: spacing.lg },
    challengeTitle: { fontFamily: fonts.display, fontSize: 18, color: '#fff', marginTop: spacing.sm, lineHeight: 24, letterSpacing: -0.2 },
    challengeSub: { fontFamily: fonts.bodySemiBold, fontSize: 13, color: 'rgba(255,255,255,0.7)', marginTop: 6 },
    readinessHeroBtn: { alignItems: 'center', justifyContent: 'center' },
    primaryCta: {
      backgroundColor: colors.primary,
      borderRadius: radii.lg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    primaryCtaText: { fontFamily: fonts.bodyBold, fontSize: 15, color: '#fff' },
    updatesChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    updatesChipText: { flex: 1, fontFamily: fonts.bodySemiBold, fontSize: 13, color: colors.text },
    weakChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      backgroundColor: colors.errorBg,
      borderRadius: radii.full,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      marginBottom: spacing.sm,
      alignSelf: 'flex-start',
    },
    weakChipText: { fontFamily: fonts.bodyBold, fontSize: 12, color: colors.error },
    pressedSoft: { opacity: 0.82, transform: [{ scale: 0.98 }] },
    cardPressed: { opacity: 0.9, transform: [{ scale: 0.99 }] },
    diagnosticCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: colors.primary,
      padding: spacing.md,
      marginBottom: spacing.md,
      ...shadows.card,
    },
    diagnosticIcon: {
      width: 40,
      height: 40,
      borderRadius: radii.md,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    diagnosticTitle: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    diagnosticSub: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
      lineHeight: 16,
    },
    heroCopy: { flex: 1, minWidth: 0, paddingRight: spacing.xs },
    heroBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.xs,
    },
    heroBadge: {
      borderRadius: radii.full,
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
    },
    heroBadgeText: { fontFamily: fonts.bodyBold, fontSize: 11, color: '#fff', letterSpacing: 0.2 },
    heroTrack: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 12,
      color: 'rgba(255,255,255,0.68)',
      marginTop: 3,
      lineHeight: 16,
    },
    heroDashboardCard: {
      backgroundColor: 'rgba(255,255,255,0.12)',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      padding: spacing.md,
      marginTop: spacing.md,
    },
    heroReadinessBlock: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    heroReadinessCopy: { flex: 1, minWidth: 0 },
    heroEmptyRing: {
      width: 58,
      height: 58,
      borderRadius: 29,
      borderWidth: 6,
      borderColor: 'rgba(255,255,255,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroEmptyRingText: { fontFamily: fonts.display, fontSize: 20, color: '#fff' },
    heroFocusLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: 'rgba(255,255,255,0.72)',
      letterSpacing: 0.35,
      textTransform: 'uppercase',
    },
    heroFocusValue: { fontFamily: fonts.display, fontSize: 18, color: '#fff', lineHeight: 22 },
    heroFocusText: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: 'rgba(255,255,255,0.78)',
      marginTop: 3,
      lineHeight: 16,
    },
    heroProgressTrack: {
      height: 6,
      borderRadius: radii.full,
      backgroundColor: 'rgba(255,255,255,0.18)',
      overflow: 'hidden',
      marginTop: spacing.sm,
    },
    heroProgressFill: { height: '100%', borderRadius: radii.full, backgroundColor: colors.accent },
    heroMetricRail: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm },
    statFreezeRow: { flexDirection: 'row', alignItems: 'center', gap: 3 },
    continueCopy: { flex: 1, minWidth: 0 },
    continueActionPill: {
      minHeight: 34,
      borderRadius: radii.full,
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      paddingHorizontal: spacing.md,
    },
    continueActionText: { fontFamily: fonts.bodyBold, fontSize: 12, color: '#fff' },
    weekLink: { flexDirection: 'row', alignItems: 'center', gap: 2, minHeight: 32 },
    weekLinkText: { fontFamily: fonts.bodyBold, fontSize: 12, color: colors.primary },
    planSummaryRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
    planSummaryPill: {
      minWidth: 54,
      minHeight: 50,
      borderRadius: 16,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
    },
    planSummaryPillWide: {
      flex: 1,
      minHeight: 50,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
      paddingHorizontal: spacing.sm,
    },
    planSummaryValue: { fontFamily: fonts.display, fontSize: 17, color: colors.primary },
    planSummaryLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: colors.textMuted,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    nextStepBlock: {
      borderRadius: 18,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.md,
      marginBottom: spacing.sm,
    },
    nextStepLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.primary,
      letterSpacing: 0.45,
      textTransform: 'uppercase',
    },
    nextStepTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 15,
      color: colors.text,
      lineHeight: 20,
      marginTop: 4,
      marginBottom: spacing.sm,
    },
    pasapathTaskCopy: { flex: 1, minWidth: 0 },
    quickActionIcon: {
      width: 38,
      height: 38,
      borderRadius: 14,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickActionCopy: { minWidth: 0 },
    quickActionSub: { fontFamily: fonts.bodySemiBold, fontSize: 11, color: colors.textMuted, marginTop: 2 },
    progressSnapshotCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    progressSnapshotTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.md,
    },
    progressSnapshotTitle: { flex: 1, minWidth: 0 },
    progressPercentBadge: {
      minWidth: 48,
      minHeight: 34,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
    },
    progressPercentText: { fontFamily: fonts.display, fontSize: 15, color: colors.primary },
    snapshotProgressTrack: {
      height: 7,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      overflow: 'hidden',
      marginTop: spacing.md,
    },
    snapshotProgressFill: { height: '100%', borderRadius: radii.full, backgroundColor: colors.primary },
    snapshotFooter: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md },
    snapshotMetric: {
      flex: 1,
      minHeight: 54,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.sm,
      justifyContent: 'center',
    },
    snapshotMetricValue: { fontFamily: fonts.display, fontSize: 17, color: colors.text },
    snapshotMetricLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: colors.textMuted,
      marginTop: 2,
      letterSpacing: 0.35,
      textTransform: 'uppercase',
    },
    sectionHeadCopy: { flex: 1, minWidth: 0 },
    sectionSub: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2, lineHeight: 16 },
    quickCopy: { flex: 1, minWidth: 0 },
    quickTopics: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.xs, marginTop: spacing.sm },
    quickTopicChip: {
      maxWidth: 124,
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.full,
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
    },
    quickTopicText: { fontFamily: fonts.bodyBold, fontSize: 11, color: colors.primaryDark },
    quickTopicMore: { fontFamily: fonts.bodyBold, fontSize: 11, color: colors.textMuted },
    quickTopicAction: {
      minWidth: 48,
      minHeight: 48,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.xs,
    },
    quickTopicActionCount: { fontFamily: fonts.display, fontSize: 14, color: colors.primary },
    quickTopicActionLabel: { fontFamily: fonts.bodyBold, fontSize: 9, color: colors.textMuted, marginTop: -2 },
    quickAllSubjectsRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      marginBottom: spacing.md,
    },
    quickAllSubjectsIcon: {
      width: 34,
      height: 34,
      borderRadius: 12,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickAllSubjectsTitle: { fontFamily: fonts.bodyBold, fontSize: 13, color: colors.text },
    quickAllSubjectsMeta: { fontFamily: fonts.bodySemiBold, fontSize: 11, color: colors.textMuted, marginTop: 2 },
    updatesIcon: {
      width: 38,
      height: 38,
      borderRadius: 14,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    updatesCopy: { flex: 1, minWidth: 0 },
    updatesChipSub: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    guestBanner: {
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.lg,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    guestBannerTitle: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    guestBannerSub: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.textMuted, marginTop: 4 },
    lowerSection: { marginTop: spacing.xs },
    homeHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      paddingBottom: spacing.xs,
    },
    homeAvatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2.5,
      borderColor: 'rgba(255,255,255,0.58)',
    },
    homeAvatarText: { fontFamily: fonts.display, fontSize: 21, color: colors.primaryDark },
    homeGreetCol: { flex: 1, minWidth: 0 },
    homeGreetTop: { fontFamily: fonts.bodySemiBold, fontSize: 14, color: 'rgba(255,255,255,0.92)' },
    homeGreetName: {
      fontFamily: fonts.display,
      fontSize: 22,
      color: '#fff',
      marginTop: 2,
      letterSpacing: -0.4,
    },
    homeFlameChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#FFEDE2',
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 12,
    },
    homeFlameChipText: { fontFamily: fonts.display, fontSize: 15, color: colors.flame },
    homeBell: {
      width: 50,
      height: 50,
      borderRadius: 16,
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeBellDot: {
      position: 'absolute',
      top: 10,
      right: 11,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.error,
      borderWidth: 1.5,
      borderColor: colors.surface,
    },
    homeBellBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.error,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 1.5,
      borderColor: colors.primaryDark,
    },
    homeBellBadgeText: { fontFamily: fonts.bodyBold, fontSize: 10, color: '#fff' },
    homeHeroCard: {
      marginHorizontal: spacing.md,
      marginTop: spacing.xs,
      borderRadius: 24,
      padding: spacing.md,
      overflow: 'hidden',
      ...shadows.soft,
    },
    homeHeroHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    homeHeroDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: 'rgba(255,255,255,0.18)',
      marginVertical: spacing.md,
    },
    homeHeroRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    homeReadinessBlock: { alignItems: 'center', gap: spacing.xs },
    homeReadinessLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: 'rgba(255,255,255,0.78)',
      letterSpacing: 0.45,
      textTransform: 'uppercase',
    },
    homeHeroExam: { color: '#fff', fontFamily: fonts.display, fontSize: 21, letterSpacing: -0.35 },
    homeHeroSub: {
      color: 'rgba(255,255,255,0.72)',
      fontFamily: fonts.bodySemiBold,
      fontSize: 12,
      marginTop: 4,
      lineHeight: 17,
    },
    homeHeroSubAccent: { color: colors.accent, fontFamily: fonts.bodyBold },
    stageWrap: { marginTop: spacing.md },
    stageTrackRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 26,
    },
    stageTrackSegment: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    stageNode: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    stageConnector: {
      flex: 1,
      height: 5,
      borderRadius: radii.full,
      marginHorizontal: 4,
    },
    stageLabelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: spacing.xs,
      gap: spacing.xs,
    },
    stageLabel: {
      flex: 1,
      fontFamily: fonts.bodyBold,
      fontSize: 9,
      color: 'rgba(255,255,255,0.72)',
      textAlign: 'center',
      lineHeight: 12,
    },
    planRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
    planGoalCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      gap: spacing.sm,
      ...shadows.card,
    },
    planGoalTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: colors.text,
      textAlign: 'center',
    },
    planGoalHint: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: colors.textMuted,
      textAlign: 'center',
    },
    qpTrioWrap: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
    qpCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    qpCardIcon: {
      width: 32,
      height: 32,
      borderRadius: 11,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing.sm,
    },
    qpCardName: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      lineHeight: 15,
      minHeight: 30,
      color: colors.text,
      letterSpacing: -0.1,
    },
    qpCardMeta: { fontFamily: fonts.bodyBold, fontSize: 11, marginTop: 2 },
    qpCardBar: {
      height: 5,
      borderRadius: radii.full,
      backgroundColor: colors.border,
      overflow: 'hidden',
      marginTop: spacing.sm,
    },
    qpCardBarFill: { height: '100%', borderRadius: radii.full },
  });
}

export function createStudyStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    header: {
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.lg,
      borderBottomLeftRadius: radii.xxl,
      borderBottomRightRadius: radii.xxl,
      overflow: 'hidden',
    },
    sparkle: { position: 'absolute', right: -30, top: 20 },
    headerNav: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.md },
    headerTag: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: 'rgba(255,255,255,0.7)',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    headerTitle: {
      fontFamily: fonts.display,
      fontSize: 28,
      color: '#fff',
      lineHeight: 32,
      letterSpacing: -0.7,
    },
    headerSub: { fontFamily: fonts.bodyMedium, fontSize: 13, color: 'rgba(255,255,255,0.75)', marginTop: 6 },
    heroStats: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md },
    noticeCard: {
      marginTop: spacing.md,
      backgroundColor: 'rgba(255,255,255,0.12)',
      borderRadius: radii.lg,
      padding: spacing.md,
    },
    noticeText: { fontFamily: fonts.bodyMedium, fontSize: 13, color: 'rgba(255,255,255,0.85)', lineHeight: 18 },
    tabs: { marginHorizontal: spacing.lg, marginTop: spacing.lg, marginBottom: spacing.xs },
    body: { padding: spacing.lg, gap: spacing.lg },
    subjectName: { fontFamily: fonts.bodyBold, fontSize: 15, color: colors.text, letterSpacing: -0.15 },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.xl,
    },
  });
}

export function createProfileStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    header: {
      paddingHorizontal: spacing.lg,
      paddingBottom: 56,
      overflow: 'hidden',
    },
    sparkle: { position: 'absolute', right: -30, top: 20 },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.lg },
    headerTitle: { fontFamily: fonts.display, fontSize: 22, color: '#fff', letterSpacing: -0.4 },
    settingsBtn: {
      width: 40,
      height: 40,
      borderRadius: radii.md,
      backgroundColor: 'rgba(255,255,255,0.15)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    avatar: {
      width: 76,
      height: 76,
      borderRadius: 22,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: 'rgba(255,255,255,0.25)',
    },
    avatarText: { fontFamily: fonts.display, fontSize: 28, color: colors.primaryDark },
    userName: { fontFamily: fonts.display, fontSize: 20, color: '#fff', letterSpacing: -0.3 },
    userSub: { fontFamily: fonts.bodyMedium, fontSize: 13, color: 'rgba(255,255,255,0.7)', marginTop: 2 },
    statsCard: {
      marginHorizontal: spacing.lg,
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.lg,
      flexDirection: 'row',
      justifyContent: 'space-around',
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    statItem: { alignItems: 'center' },
    statVal: { fontFamily: fonts.display, fontSize: 22, letterSpacing: -0.5 },
    statLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 4,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    section: { paddingHorizontal: spacing.lg, marginTop: spacing.lg },
    sectionTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: colors.text, letterSpacing: -0.15, marginBottom: spacing.sm },
    sessionCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.md,
      marginTop: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sessionTitle: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    sessionDate: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    sessionScore: { fontFamily: fonts.display, fontSize: 22, color: colors.primary },
  });
}

export function createLeaderboardStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    header: {
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.lg,
      borderBottomLeftRadius: radii.xxl,
      borderBottomRightRadius: radii.xxl,
    },
    headerTitle: { fontFamily: fonts.display, fontSize: 22, color: '#fff', letterSpacing: -0.4 },
    headerSub: { fontFamily: fonts.bodyMedium, fontSize: 13, color: 'rgba(255,255,255,0.75)', marginTop: 6 },
    body: { padding: spacing.lg },
    podium: { flexDirection: 'row', justifyContent: 'center', alignItems: 'flex-end', gap: spacing.sm, marginBottom: spacing.lg },
    podiumSlot: { alignItems: 'center', flex: 1, backgroundColor: colors.surface, borderRadius: radii.xl, padding: spacing.md },
    podiumFirst: { transform: [{ translateY: -8 }], borderWidth: 2, borderColor: colors.accent },
    podiumRank: { fontFamily: fonts.bodyBold, fontSize: 12, color: colors.textMuted },
    podiumAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: spacing.sm,
    },
    podiumInitial: { fontFamily: fonts.display, fontSize: 18, color: colors.primary },
    podiumName: { fontFamily: fonts.bodyBold, fontSize: 13, color: colors.text, maxWidth: 90 },
    podiumXp: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.accentDark, marginTop: 4 },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.md,
      marginBottom: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    rowYou: { borderWidth: 1.5, borderColor: colors.primary },
    rowRank: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.textMuted, width: 28 },
    rowAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowInitial: { fontFamily: fonts.bodyBold, fontSize: 13, color: colors.primary },
    rowName: { flex: 1, fontFamily: fonts.bodySemiBold, fontSize: 14, color: colors.text },
    rowXp: { fontFamily: fonts.display, fontSize: 16, color: colors.primary },
    youChip: { alignItems: 'center', marginTop: spacing.md },
  });
}

export function createQuizStyles(theme: AppTheme) {
  const { colors, type, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.sm,
    },
    closeBtn: {
      width: 36,
      height: 36,
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    segments: { flex: 1, flexDirection: 'row', gap: 4 },
    segment: { flex: 1, height: 6, borderRadius: radii.full, backgroundColor: colors.border },
    segmentDone: { backgroundColor: colors.success },
    segmentActive: { backgroundColor: colors.primary },
    progressWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    progressTrack: {
      flex: 1,
      height: 8,
      borderRadius: radii.full,
      backgroundColor: colors.border,
      overflow: 'hidden',
    },
    progressFill: { height: '100%', borderRadius: radii.full, backgroundColor: colors.primary },
    progressCounter: { ...type.label, fontSize: 13, color: colors.text },
    progressCounterMute: { color: colors.textMuted },
    timer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.accentLight,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: radii.full,
    },
    timerText: { fontFamily: type.label.fontFamily, fontSize: 12, color: colors.accentDark },
    mockBanner: {
      marginHorizontal: spacing.lg,
      marginBottom: spacing.sm,
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.md,
      padding: spacing.sm,
    },
    mockBannerText: {
      ...type.caption,
      textTransform: 'none',
      color: theme.isDark ? colors.text : colors.primaryDark,
      textAlign: 'center',
    },
    meta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.sm,
    },
    metaText: { ...type.caption, textTransform: 'uppercase', letterSpacing: 0.6 },
    questionCard: {
      marginHorizontal: spacing.lg,
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.lg,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    stem: { ...type.label, fontSize: 19, lineHeight: 26, letterSpacing: -0.2 },
    options: { paddingHorizontal: spacing.lg, paddingTop: spacing.md },
    explanation: {
      marginHorizontal: spacing.lg,
      marginTop: spacing.sm,
      backgroundColor: colors.warnBg,
      borderRadius: radii.lg,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.warnBorder,
    },
    explanationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },
    explanationTitle: { ...type.subtitle, color: theme.isDark ? colors.text : colors.primaryDark },
    langToggle: { flexDirection: 'row', gap: 4, backgroundColor: colors.surface, borderRadius: radii.sm, padding: 2 },
    langBtn: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
    langBtnActive: { backgroundColor: colors.primary },
    langText: { ...type.caption, textTransform: 'none' },
    langTextActive: { color: '#fff' },
    explanationBody: { ...type.body, fontSize: 14 },
    hintRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.warnBg,
      borderWidth: 1,
      borderColor: colors.warnBorder,
      borderRadius: radii.lg,
      padding: spacing.md,
      marginBottom: spacing.sm,
    },
    hintText: { flex: 1, fontFamily: type.bodySemiBold.fontFamily, fontSize: 12, color: theme.isDark ? colors.text : colors.primaryDark },
    hintXp: { fontFamily: type.label.fontFamily, color: colors.accentDark },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.md,
      backgroundColor: colors.background,
    },
  });
}

export function createListScreenStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.md,
    },
    backBtn: { width: 28, height: 28, justifyContent: 'center' },
    title: { fontFamily: fonts.display, fontSize: 24, color: colors.text, marginTop: spacing.sm },
    sub: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.textMuted, marginTop: 4 },
    card: {
      marginHorizontal: spacing.lg,
      marginBottom: spacing.sm,
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    cardSubject: { fontFamily: fonts.bodyBold, fontSize: 11, color: colors.primary, textTransform: 'uppercase' },
    cardStem: { fontFamily: fonts.bodySemiBold, fontSize: 14, color: colors.text, marginTop: 4 },
    cardMeta: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.textMuted, marginTop: 6 },
  });
}

export function createFlashcardStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii } = theme;
  return StyleSheet.create({
    root: { flex: 1 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.md,
    },
    topLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: colors.textLight,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    topTitle: { fontFamily: fonts.bodyBold, fontSize: 15, color: colors.text, marginTop: 1 },
    counter: {
      textAlign: 'center',
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: spacing.md,
    },
    stackArea: { flex: 1, paddingHorizontal: spacing.lg, justifyContent: 'center' },
    cardFront: {
      minHeight: 380,
      backgroundColor: colors.surface,
      borderRadius: 26,
      padding: spacing.lg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardBody: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xl },
    term: {
      fontFamily: fonts.display,
      fontSize: 32,
      color: theme.isDark ? colors.text : colors.primaryDark,
      textAlign: 'center',
      lineHeight: 38,
    },
    termSmall: { fontSize: 18, lineHeight: 26 },
    topicLbl: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.textMuted, marginTop: spacing.sm },
    flipHint: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
    flipText: { fontFamily: fonts.bodyBold, fontSize: 12, color: colors.textLight },
    actions: { flexDirection: 'row', gap: spacing.sm, paddingHorizontal: spacing.lg },
    actionBtn: { flex: 1 },
    completeBanner: {
      position: 'absolute',
      bottom: 120,
      left: spacing.lg,
      right: spacing.lg,
      backgroundColor: colors.successBg,
      borderRadius: radii.lg,
      padding: spacing.md,
      alignItems: 'center',
    },
    completeText: { fontFamily: fonts.bodyBold, color: colors.success },
  });
}

export function createResultStyles(theme: AppTheme) {
  const { colors, fonts, spacing } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    hero: {
      paddingHorizontal: spacing.lg,
      paddingBottom: 50,
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      alignItems: 'center',
    },
    sparkleA: { position: 'absolute', top: 80, left: 40 },
    heroLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: 'rgba(255,255,255,0.7)',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    heroTitle: {
      fontFamily: fonts.display,
      fontSize: 28,
      color: '#fff',
      textAlign: 'center',
      marginTop: spacing.sm,
      letterSpacing: -0.5,
    },
    statsRow: { flexDirection: 'row', gap: spacing.sm, padding: spacing.lg, marginTop: -30 },
    statCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: spacing.md,
      alignItems: 'center',
    },
    statLbl: { fontFamily: fonts.bodyBold, fontSize: 10, color: colors.textLight, letterSpacing: 0.5 },
    statVal: { fontFamily: fonts.display, fontSize: 22, marginTop: 4, letterSpacing: -0.4 },
    reviewBox: {
      marginHorizontal: spacing.lg,
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: spacing.lg,
      marginBottom: spacing.md,
    },
    reviewTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: colors.text, marginBottom: spacing.sm },
    reviewEmpty: { fontFamily: fonts.bodyMedium, fontSize: 14, color: colors.textMuted },
    reviewItem: { borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.sm },
    reviewHead: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
    reviewQ: { flex: 1, fontFamily: fonts.bodySemiBold, fontSize: 14, color: colors.text },
    reviewBody: { marginTop: spacing.sm, gap: spacing.xs },
    explanation: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.textMuted, marginTop: spacing.sm },
    reportBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing.sm, paddingVertical: 4 },
    reportBtnText: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.textMuted },
    actions: { paddingHorizontal: spacing.lg, marginTop: spacing.sm },
  });
}

export function createAnalyticsStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii, shadows, isDark } = theme;
  const cardShadow = isDark ? {} : shadows.card;
  const headlineBlue = isDark ? colors.text : colors.primaryDark;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.sm,
    },
    backBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: -4,
    },
    headerTitle: {
      fontFamily: fonts.display,
      fontSize: 26,
      color: headlineBlue,
      letterSpacing: -0.4,
    },
    body: { paddingHorizontal: spacing.md, paddingTop: spacing.xs },
    summaryCard: {
      backgroundColor: isDark ? colors.surface : colors.surface,
      borderRadius: radii.xl,
      padding: spacing.lg,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: isDark ? colors.border : colors.primaryMuted,
      borderTopWidth: 3,
      borderTopColor: colors.primary,
      ...cardShadow,
    },
    summarySettings: {
      position: 'absolute',
      top: spacing.md,
      right: spacing.md,
      width: 40,
      height: 40,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    summaryTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 17,
      color: headlineBlue,
      paddingRight: 44,
      letterSpacing: -0.2,
    },
    summarySub: {
      fontFamily: fonts.bodyMedium,
      fontSize: 14,
      color: colors.textMuted,
      marginTop: 4,
      lineHeight: 20,
    },
    summarySegments: { marginTop: spacing.md },
    weakBox: {
      marginTop: spacing.md,
      backgroundColor: colors.errorBg,
      borderRadius: radii.md,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm + 2,
    },
    weakBoxText: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 13,
      color: colors.error,
      lineHeight: 19,
    },
    subjectCard: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.lg,
      marginBottom: spacing.md,
      borderWidth: isDark ? 1 : 0,
      borderColor: colors.border,
      ...cardShadow,
    },
    subjectHead: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: spacing.md,
      gap: spacing.sm,
    },
    subjectName: {
      fontFamily: fonts.bodyBold,
      fontSize: 17,
      color: headlineBlue,
      flex: 1,
      letterSpacing: -0.2,
    },
    subjectPct: {
      fontFamily: fonts.display,
      fontSize: 22,
      color: colors.primary,
      letterSpacing: -0.3,
    },
    topicRow: {
      marginTop: spacing.md,
      paddingTop: spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    topicRowFirst: {
      marginTop: 0,
      paddingTop: 0,
      borderTopWidth: 0,
    },
    topicMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.md,
      marginBottom: spacing.sm,
    },
    topicName: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 15,
      color: headlineBlue,
      flex: 1,
      lineHeight: 20,
    },
    topicPct: {
      fontFamily: fonts.bodyMedium,
      fontSize: 13,
      color: colors.textMuted,
      textAlign: 'right',
      flexShrink: 0,
    },
    topicBar: { height: 6, borderRadius: 3 },
    cta: { marginTop: spacing.xs },
  });
}
