import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../hooks/use-app-theme';

export function createDashboardStyles(theme: AppTheme) {
  const { colors, fonts, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    hero: {
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.lg,
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
      overflow: 'hidden',
    },
    sparkleTop: { position: 'absolute', top: 72, left: spacing.lg },
    sparkleMid: { position: 'absolute', bottom: 48, right: spacing.xl, opacity: 0.5 },
    heroTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: spacing.md,
      marginBottom: spacing.xs,
    },
    heroGreet: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 13,
      color: 'rgba(255,255,255,0.72)',
      letterSpacing: 0.2,
      textTransform: 'none',
    },
    heroName: {
      fontFamily: fonts.display,
      fontSize: 21,
      color: '#fff',
      marginTop: 4,
      letterSpacing: -0.5,
      lineHeight: 28,
    },
    bellBtn: {
      width: 44,
      height: 44,
      borderRadius: radii.lg,
      backgroundColor: 'rgba(255,255,255,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    statRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md },
    statPill: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: 'rgba(255,255,255,0.11)',
      borderRadius: radii.lg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      minWidth: 0,
    },
    statPillReadiness: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
      backgroundColor: 'rgba(255,255,255,0.11)',
      borderRadius: radii.lg,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.xs,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    statIconWrap: {
      width: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statTextWrap: { flex: 1, minWidth: 0 },
    pctBadge: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    pctBadgeText: { fontFamily: fonts.display, fontSize: 11, color: colors.primary },
    statVal: { fontFamily: fonts.display, fontSize: 17, color: '#fff', lineHeight: 20, letterSpacing: -0.3 },
    statLbl: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: 'rgba(255,255,255,0.65)',
      marginTop: 2,
      lineHeight: 13,
    },
    statLblCenter: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: 'rgba(255,255,255,0.65)',
      textAlign: 'center',
      lineHeight: 13,
    },
    sectionPad: { paddingHorizontal: spacing.md, paddingTop: spacing.md },
    continueCard: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    continueRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.sm },
    continueIcon: {
      width: 46,
      height: 46,
      borderRadius: 16,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    continueAbbr: { fontFamily: fonts.bodyBold, color: colors.primary, fontSize: 15 },
    continueLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.textLight,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    continueTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: colors.text, marginTop: 2, letterSpacing: -0.15 },
    continueMeta: { fontFamily: fonts.bodySemiBold, fontSize: 13, color: colors.textMuted },
    pasapathCard: {
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    pasapathHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    pasapathLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.primary,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    pasapathMeta: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.textMuted, marginTop: 4, marginBottom: spacing.sm },
    pasapathTask: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingVertical: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    pasapathTaskTitle: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    pasapathTaskSub: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    quickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
    quickAction: {
      width: '48%',
      minHeight: 92,
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'space-between',
    },
    quickActionText: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    goalCard: {
      borderRadius: 20,
      padding: spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      marginBottom: spacing.lg,
      borderWidth: 1,
      borderColor: 'rgba(245,166,35,0.2)',
      ...shadows.card,
    },
    goalLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.accentDark,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    goalTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: colors.text, marginTop: 2, letterSpacing: -0.15 },
    goalHint: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 3 },
    sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: spacing.sm },
    sectionTitle: { fontFamily: fonts.bodyBold, fontSize: 17, color: colors.text, letterSpacing: -0.15 },
    quickRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: spacing.md,
      marginBottom: spacing.sm,
      minHeight: 88,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    quickIcon: { width: 44, height: 44, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
    quickName: { fontFamily: fonts.bodyBold, fontSize: 15, color: colors.text, letterSpacing: -0.15 },
    quickMeta: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    playBtn: { width: 36, height: 36, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
    challengeCard: { borderRadius: radii.xl, padding: spacing.lg, marginTop: spacing.md, marginBottom: spacing.lg },
    challengeTitle: { fontFamily: fonts.display, fontSize: 18, color: '#fff', marginTop: spacing.sm, lineHeight: 24, letterSpacing: -0.2 },
    challengeSub: { fontFamily: fonts.bodySemiBold, fontSize: 13, color: 'rgba(255,255,255,0.7)', marginTop: 6 },
    readinessHeroBtn: { alignItems: 'center', justifyContent: 'center' },
    primaryCta: {
      backgroundColor: colors.primary,
      borderRadius: radii.lg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    primaryCtaText: { fontFamily: fonts.bodyBold, fontSize: 15, color: '#fff' },
    updatesChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    updatesChipText: { flex: 1, fontFamily: fonts.bodySemiBold, fontSize: 13, color: colors.text },
    weakChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      backgroundColor: colors.errorBg,
      borderRadius: radii.full,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      marginBottom: spacing.sm,
      alignSelf: 'flex-start',
    },
    weakChipText: { fontFamily: fonts.bodyBold, fontSize: 12, color: colors.error },
    pressedSoft: { opacity: 0.82, transform: [{ scale: 0.98 }] },
    cardPressed: { opacity: 0.9, transform: [{ scale: 0.99 }] },
    heroCopy: { flex: 1, minWidth: 0, paddingRight: spacing.xs },
    heroBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.xs,
    },
    heroBadge: {
      borderRadius: radii.full,
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
    },
    heroBadgeText: { fontFamily: fonts.bodyBold, fontSize: 11, color: '#fff', letterSpacing: 0.2 },
    heroTrack: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 12,
      color: 'rgba(255,255,255,0.68)',
      marginTop: 3,
      lineHeight: 16,
    },
    heroDashboardCard: {
      backgroundColor: 'rgba(255,255,255,0.12)',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      padding: spacing.md,
      marginTop: spacing.md,
    },
    heroReadinessBlock: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    heroReadinessCopy: { flex: 1, minWidth: 0 },
    heroEmptyRing: {
      width: 58,
      height: 58,
      borderRadius: 29,
      borderWidth: 6,
      borderColor: 'rgba(255,255,255,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroEmptyRingText: { fontFamily: fonts.display, fontSize: 20, color: '#fff' },
    heroFocusLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: 'rgba(255,255,255,0.72)',
      letterSpacing: 0.35,
      textTransform: 'uppercase',
    },
    heroFocusValue: { fontFamily: fonts.display, fontSize: 18, color: '#fff', lineHeight: 22 },
    heroFocusText: {
      fontFamily: fonts.bodyMedium,
      fontSize: 12,
      color: 'rgba(255,255,255,0.78)',
      marginTop: 3,
      lineHeight: 16,
    },
    heroProgressTrack: {
      height: 6,
      borderRadius: radii.full,
      backgroundColor: 'rgba(255,255,255,0.18)',
      overflow: 'hidden',
      marginTop: spacing.sm,
    },
    heroProgressFill: { height: '100%', borderRadius: radii.full, backgroundColor: colors.accent },
    heroMetricRail: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm },
    statFreezeRow: { flexDirection: 'row', alignItems: 'center', gap: 3 },
    continueCopy: { flex: 1, minWidth: 0 },
    continueActionPill: {
      minHeight: 34,
      borderRadius: radii.full,
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      paddingHorizontal: spacing.md,
    },
    continueActionText: { fontFamily: fonts.bodyBold, fontSize: 12, color: '#fff' },
    weekLink: { flexDirection: 'row', alignItems: 'center', gap: 2, minHeight: 32 },
    weekLinkText: { fontFamily: fonts.bodyBold, fontSize: 12, color: colors.primary },
    planSummaryRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
    planSummaryPill: {
      minWidth: 54,
      minHeight: 50,
      borderRadius: 16,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
    },
    planSummaryPillWide: {
      flex: 1,
      minHeight: 50,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
      paddingHorizontal: spacing.sm,
    },
    planSummaryValue: { fontFamily: fonts.display, fontSize: 17, color: colors.primary },
    planSummaryLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: colors.textMuted,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    nextStepBlock: {
      borderRadius: 18,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.md,
      marginBottom: spacing.sm,
    },
    nextStepLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.primary,
      letterSpacing: 0.45,
      textTransform: 'uppercase',
    },
    nextStepTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 15,
      color: colors.text,
      lineHeight: 20,
      marginTop: 4,
      marginBottom: spacing.sm,
    },
    pasapathTaskCopy: { flex: 1, minWidth: 0 },
    quickActionIcon: {
      width: 38,
      height: 38,
      borderRadius: 14,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickActionCopy: { minWidth: 0 },
    quickActionSub: { fontFamily: fonts.bodySemiBold, fontSize: 11, color: colors.textMuted, marginTop: 2 },
    progressSnapshotCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    progressSnapshotTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.md,
    },
    progressSnapshotTitle: { flex: 1, minWidth: 0 },
    progressPercentBadge: {
      minWidth: 48,
      minHeight: 34,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
    },
    progressPercentText: { fontFamily: fonts.display, fontSize: 15, color: colors.primary },
    snapshotProgressTrack: {
      height: 7,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      overflow: 'hidden',
      marginTop: spacing.md,
    },
    snapshotProgressFill: { height: '100%', borderRadius: radii.full, backgroundColor: colors.primary },
    snapshotFooter: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md },
    snapshotMetric: {
      flex: 1,
      minHeight: 54,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.sm,
      justifyContent: 'center',
    },
    snapshotMetricValue: { fontFamily: fonts.display, fontSize: 17, color: colors.text },
    snapshotMetricLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: colors.textMuted,
      marginTop: 2,
      letterSpacing: 0.35,
      textTransform: 'uppercase',
    },
    sectionHeadCopy: { flex: 1, minWidth: 0 },
    sectionSub: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2, lineHeight: 16 },
    quickCopy: { flex: 1, minWidth: 0 },
    quickTopics: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.xs, marginTop: spacing.sm },
    quickTopicChip: {
      maxWidth: 124,
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.full,
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
    },
    quickTopicText: { fontFamily: fonts.bodyBold, fontSize: 11, color: colors.primaryDark },
    quickTopicMore: { fontFamily: fonts.bodyBold, fontSize: 11, color: colors.textMuted },
    quickTopicAction: {
      minWidth: 48,
      minHeight: 48,
      borderRadius: radii.full,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.xs,
    },
    quickTopicActionCount: { fontFamily: fonts.display, fontSize: 14, color: colors.primary },
    quickTopicActionLabel: { fontFamily: fonts.bodyBold, fontSize: 9, color: colors.textMuted, marginTop: -2 },
    quickAllSubjectsRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      marginBottom: spacing.md,
    },
    quickAllSubjectsIcon: {
      width: 34,
      height: 34,
      borderRadius: 12,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickAllSubjectsTitle: { fontFamily: fonts.bodyBold, fontSize: 13, color: colors.text },
    quickAllSubjectsMeta: { fontFamily: fonts.bodySemiBold, fontSize: 11, color: colors.textMuted, marginTop: 2 },
    updatesIcon: {
      width: 38,
      height: 38,
      borderRadius: 14,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    updatesCopy: { flex: 1, minWidth: 0 },
    updatesChipSub: { fontFamily: fonts.bodySemiBold, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    guestBanner: {
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.lg,
      padding: spacing.md,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    guestBannerTitle: { fontFamily: fonts.bodyBold, fontSize: 14, color: colors.text },
    guestBannerSub: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.textMuted, marginTop: 4 },
    lowerSection: { marginTop: spacing.xs },
    homeHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      paddingBottom: spacing.xs,
    },
    homeAvatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2.5,
      borderColor: 'rgba(255,255,255,0.58)',
    },
    homeAvatarText: { fontFamily: fonts.display, fontSize: 21, color: colors.primaryDark },
    homeGreetCol: { flex: 1, minWidth: 0 },
    homeGreetTop: { fontFamily: fonts.bodySemiBold, fontSize: 14, color: 'rgba(255,255,255,0.92)' },
    homeGreetName: {
      fontFamily: fonts.display,
      fontSize: 22,
      color: '#fff',
      marginTop: 2,
      letterSpacing: -0.4,
    },
    homeFlameChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#FFEDE2',
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 12,
    },
    homeFlameChipText: { fontFamily: fonts.display, fontSize: 15, color: colors.flame },
    homeBell: {
      width: 50,
      height: 50,
      borderRadius: 16,
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeBellDot: {
      position: 'absolute',
      top: 10,
      right: 11,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.error,
      borderWidth: 1.5,
      borderColor: colors.surface,
    },
    homeBellBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.error,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 1.5,
      borderColor: colors.primaryDark,
    },
    homeBellBadgeText: { fontFamily: fonts.bodyBold, fontSize: 10, color: '#fff' },
    homeHeroCard: {
      marginHorizontal: spacing.md,
      marginTop: spacing.xs,
      borderRadius: 24,
      padding: spacing.md,
      overflow: 'hidden',
      ...shadows.soft,
    },
    homeHeroHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    homeHeroDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: 'rgba(255,255,255,0.18)',
      marginVertical: spacing.md,
    },
    homeHeroRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    homeReadinessBlock: { alignItems: 'center', gap: spacing.xs },
    homeReadinessLabel: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: 'rgba(255,255,255,0.78)',
      letterSpacing: 0.45,
      textTransform: 'uppercase',
    },
    homeHeroExam: { color: '#fff', fontFamily: fonts.display, fontSize: 21, letterSpacing: -0.35 },
    homeHeroSub: {
      color: 'rgba(255,255,255,0.72)',
      fontFamily: fonts.bodySemiBold,
      fontSize: 12,
      marginTop: 4,
      lineHeight: 17,
    },
    homeHeroSubAccent: { color: colors.accent, fontFamily: fonts.bodyBold },
    stageWrap: { marginTop: spacing.md },
    stageTrackRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 26,
    },
    stageTrackSegment: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    stageNode: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    stageConnector: {
      flex: 1,
      height: 5,
      borderRadius: radii.full,
      marginHorizontal: 4,
    },
    stageLabelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: spacing.xs,
      gap: spacing.xs,
    },
    stageLabel: {
      flex: 1,
      fontFamily: fonts.bodyBold,
      fontSize: 9,
      color: 'rgba(255,255,255,0.72)',
      textAlign: 'center',
      lineHeight: 12,
    },
    planRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
    planGoalCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      gap: spacing.sm,
      ...shadows.card,
    },
    planGoalTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 12,
      color: colors.text,
      textAlign: 'center',
    },
    planGoalHint: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: colors.textMuted,
      textAlign: 'center',
    },
    planContinueCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'space-between',
      ...shadows.card,
    },
    planContinueLbl: {
      fontFamily: fonts.bodyBold,
      fontSize: 10,
      color: colors.textLight,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    planContinueTitle: {
      fontFamily: fonts.bodyBold,
      fontSize: 13,
      color: colors.text,
      marginTop: 5,
      letterSpacing: -0.15,
    },
    planContinueMeta: {
      fontFamily: fonts.bodySemiBold,
      fontSize: 10,
      color: colors.textMuted,
      marginTop: 2,
    },
    planResumeBtn: {
      marginTop: spacing.xs,
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.sm,
      paddingVertical: 7,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    planResumeBtnText: { fontFamily: fonts.bodyBold, fontSize: 13, color: colors.primary },
    qpTrioWrap: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
    qpCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: radii.lg,
      padding: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    qpCardIcon: {
      width: 32,
      height: 32,
      borderRadius: 11,
      backgroundColor: colors.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing.sm,
    },
    qpCardName: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      lineHeight: 15,
      minHeight: 30,
      color: colors.text,
      letterSpacing: -0.1,
    },
    qpCardMeta: { fontFamily: fonts.bodyBold, fontSize: 11, marginTop: 2 },
    qpCardBar: {
      height: 5,
      borderRadius: radii.full,
      backgroundColor: colors.border,
      overflow: 'hidden',
      marginTop: spacing.sm,
    },
    qpCardBarFill: { height: '100%', borderRadius: radii.full },
    plusUpsell: {
      borderRadius: radii.lg,
      padding: spacing.md,
      marginBottom: spacing.md,
      overflow: 'hidden',
      minHeight: 118,
      position: 'relative',
    },
    plusUpsellBadge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.accent,
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: radii.full,
    },
    plusUpsellBadgeText: {
      fontFamily: fonts.bodyBold,
      fontSize: 11,
      color: colors.primaryDark,
      letterSpacing: 0.4,
    },
    plusUpsellTitle: {
      color: '#fff',
      fontFamily: fonts.display,
      fontSize: 17,
      marginTop: spacing.sm,
      lineHeight: 22,
      letterSpacing: -0.2,
      maxWidth: '68%',
    },
    plusUpsellSub: {
      color: 'rgba(255,255,255,0.66)',
      fontFamily: fonts.bodySemiBold,
      fontSize: 11,
      marginTop: 5,
      maxWidth: '64%',
    },
    plusUpsellArt: {
      position: 'absolute',
      right: spacing.lg,
      bottom: spacing.lg,
      width: 86,
      height: 72,
      borderRadius: radii.lg,
      backgroundColor: 'rgba(255,255,255,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
      transform: [{ rotate: '-8deg' }],
    },
    plusUpsellFootnote: {
      textAlign: 'center',
      fontFamily: fonts.bodySemiBold,
      fontSize: 11,
      color: colors.textMuted,
      marginBottom: spacing.md,
    },
    plusArtScene: {
      position: 'absolute',
      right: spacing.md,
      bottom: spacing.sm,
      width: 108,
      height: 92,
      alignItems: 'center',
      justifyContent: 'center',
    },
    plusArtGlow: {
      position: 'absolute',
      width: 92,
      height: 62,
      borderRadius: 24,
      backgroundColor: 'rgba(255,255,255,0.16)',
      bottom: 6,
    },
    plusArtBase: {
      width: 72,
      height: 54,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.17)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.22)',
      transform: [{ rotate: '8deg' }],
    },
    plusArtIcon: { width: 38, height: 38, borderRadius: 12 },
    plusArtCrown: {
      position: 'absolute',
      top: 2,
      right: 18,
      width: 42,
      height: 34,
      borderRadius: 15,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.36)',
    },
    plusArtSparkleA: { position: 'absolute', left: 12, top: 18 },
    plusArtSparkleB: { position: 'absolute', right: 0, top: 34 },
  });
}
