import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../hooks/use-app-theme';

export function createQuizStyles(theme: AppTheme) {
  const { colors, type, spacing, radii, shadows } = theme;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.sm,
    },
    closeBtn: {
      width: 36,
      height: 36,
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    segments: { flex: 1, flexDirection: 'row', gap: 4 },
    segment: { flex: 1, height: 6, borderRadius: radii.full, backgroundColor: colors.border },
    segmentDone: { backgroundColor: colors.success },
    segmentActive: { backgroundColor: colors.primary },
    progressWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    progressTrack: {
      flex: 1,
      height: 8,
      borderRadius: radii.full,
      backgroundColor: colors.border,
      overflow: 'hidden',
    },
    progressFill: { height: '100%', borderRadius: radii.full, backgroundColor: colors.primary },
    progressCounter: { ...type.label, fontSize: 13, color: colors.text },
    progressCounterMute: { color: colors.textMuted },
    timer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.accentLight,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: radii.full,
    },
    timerText: { fontFamily: type.label.fontFamily, fontSize: 12, color: colors.accentDark },
    mockBanner: {
      marginHorizontal: spacing.lg,
      marginBottom: spacing.sm,
      backgroundColor: colors.primaryMuted,
      borderRadius: radii.md,
      padding: spacing.sm,
    },
    mockBannerText: {
      ...type.caption,
      textTransform: 'none',
      color: theme.isDark ? colors.text : colors.primaryDark,
      textAlign: 'center',
    },
    meta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.sm,
    },
    metaText: { ...type.caption, textTransform: 'uppercase', letterSpacing: 0.6 },
    questionCard: {
      marginHorizontal: spacing.lg,
      backgroundColor: colors.surface,
      borderRadius: radii.xl,
      padding: spacing.lg,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    stem: { ...type.label, fontSize: 19, lineHeight: 26, letterSpacing: -0.2 },
    options: { paddingHorizontal: spacing.lg, paddingTop: spacing.md },
    explanation: {
      marginHorizontal: spacing.lg,
      marginTop: spacing.sm,
      backgroundColor: colors.warnBg,
      borderRadius: radii.lg,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.warnBorder,
    },
    explanationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },
    explanationTitle: { ...type.subtitle, color: theme.isDark ? colors.text : colors.primaryDark },
    langToggle: { flexDirection: 'row', gap: 4, backgroundColor: colors.surface, borderRadius: radii.sm, padding: 2 },
    langBtn: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
    langBtnActive: { backgroundColor: colors.primary },
    langText: { ...type.caption, textTransform: 'none' },
    langTextActive: { color: '#fff' },
    explanationBody: { ...type.body, fontSize: 14 },
    hintRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.warnBg,
      borderWidth: 1,
      borderColor: colors.warnBorder,
      borderRadius: radii.lg,
      padding: spacing.md,
      marginBottom: spacing.sm,
    },
    hintText: { flex: 1, fontFamily: type.bodySemiBold.fontFamily, fontSize: 12, color: theme.isDark ? colors.text : colors.primaryDark },
    hintXp: { fontFamily: type.label.fontFamily, color: colors.accentDark },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.md,
      backgroundColor: colors.background,
    },
  });
}
