/** Generated by `npm run db:gen-types` — do not edit manually. */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      achievement_badges: {
        Row: {
          description: string
          emoji: string
          id: string
          slug: string
          sort_order: number
          title: string
        }
        Insert: {
          description: string
          emoji?: string
          id?: string
          slug: string
          sort_order?: number
          title: string
        }
        Update: {
          description?: string
          emoji?: string
          id?: string
          slug?: string
          sort_order?: number
          title?: string
        }
        Relationships: []
      }
      admin_logs: {
        Row: {
          action: string
          admin_id: string
          created_at: string
          entity_id: string | null
          entity_type: string | null
          id: string
          metadata: Json | null
        }
        Insert: {
          action: string
          admin_id: string
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          metadata?: Json | null
        }
        Update: {
          action?: string
          admin_id?: string
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          metadata?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_logs_admin_id_fkey"
            columns: ["admin_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_explanation_usage: {
        Row: {
          count: number
          usage_date: string
          user_id: string
        }
        Insert: {
          count?: number
          usage_date?: string
          user_id: string
        }
        Update: {
          count?: number
          usage_date?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_explanation_usage_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      announcements: {
        Row: {
          body: string
          exam_type_id: string | null
          id: string
          published_at: string
          title: string
        }
        Insert: {
          body: string
          exam_type_id?: string | null
          id?: string
          published_at?: string
          title: string
        }
        Update: {
          body?: string
          exam_type_id?: string | null
          id?: string
          published_at?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "announcements_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      barkada_challenge_results: {
        Row: {
          challenge_id: string
          correct_count: number
          score_percent: number
          session_id: string | null
          submitted_at: string
          total_count: number
          user_id: string
        }
        Insert: {
          challenge_id: string
          correct_count: number
          score_percent: number
          session_id?: string | null
          submitted_at?: string
          total_count: number
          user_id: string
        }
        Update: {
          challenge_id?: string
          correct_count?: number
          score_percent?: number
          session_id?: string | null
          submitted_at?: string
          total_count?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "barkada_challenge_results_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "barkada_challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "barkada_challenge_results_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "quiz_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "barkada_challenge_results_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      barkada_challenges: {
        Row: {
          created_at: string
          created_by: string
          exam_slug: string
          expires_at: string
          group_id: string
          id: string
          question_count: number
          status: string
        }
        Insert: {
          created_at?: string
          created_by: string
          exam_slug: string
          expires_at?: string
          group_id: string
          id?: string
          question_count?: number
          status?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          exam_slug?: string
          expires_at?: string
          group_id?: string
          id?: string
          question_count?: number
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "barkada_challenges_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "barkada_challenges_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "barkada_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      barkada_groups: {
        Row: {
          created_at: string
          exam_type_id: string
          id: string
          invite_code: string
          name: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          exam_type_id: string
          id?: string
          invite_code: string
          name: string
          owner_id: string
        }
        Update: {
          created_at?: string
          exam_type_id?: string
          id?: string
          invite_code?: string
          name?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "barkada_groups_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "barkada_groups_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      barkada_members: {
        Row: {
          group_id: string
          joined_at: string
          user_id: string
        }
        Insert: {
          group_id: string
          joined_at?: string
          user_id: string
        }
        Update: {
          group_id?: string
          joined_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "barkada_members_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "barkada_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "barkada_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      bookmarks: {
        Row: {
          created_at: string
          id: string
          question_id: string | null
          review_material_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          question_id?: string | null
          review_material_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          question_id?: string | null
          review_material_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookmarks_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookmarks_review_material_id_fkey"
            columns: ["review_material_id"]
            isOneToOne: false
            referencedRelation: "review_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookmarks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      content_changelog: {
        Row: {
          body: string
          exam_type_id: string | null
          id: string
          published_at: string
          title: string
        }
        Insert: {
          body: string
          exam_type_id?: string | null
          id?: string
          published_at?: string
          title: string
        }
        Update: {
          body?: string
          exam_type_id?: string | null
          id?: string
          published_at?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_changelog_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      diagnostic_sessions: {
        Row: {
          completed_at: string | null
          duration_seconds: number | null
          exam_type_id: string
          id: string
          item_count: number
          score_by_topic: Json
          score_percent: number | null
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          duration_seconds?: number | null
          exam_type_id: string
          id?: string
          item_count: number
          score_by_topic?: Json
          score_percent?: number | null
          user_id: string
        }
        Update: {
          completed_at?: string | null
          duration_seconds?: number | null
          exam_type_id?: string
          id?: string
          item_count?: number
          score_by_topic?: Json
          score_percent?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "diagnostic_sessions_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diagnostic_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      exam_blueprints: {
        Row: {
          content_targets: Json
          created_at: string
          effective_date: string
          exam_type_id: string
          id: string
          mock_exam_config: Json
          official_source_url: string | null
          topic_weights: Json
          version: string
        }
        Insert: {
          content_targets?: Json
          created_at?: string
          effective_date: string
          exam_type_id: string
          id?: string
          mock_exam_config?: Json
          official_source_url?: string | null
          topic_weights?: Json
          version: string
        }
        Update: {
          content_targets?: Json
          created_at?: string
          effective_date?: string
          exam_type_id?: string
          id?: string
          mock_exam_config?: Json
          official_source_url?: string | null
          topic_weights?: Json
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "exam_blueprints_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      exam_categories: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          name: string
          slug: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          slug: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          slug?: string
          sort_order?: number
        }
        Relationships: []
      }
      exam_schedules: {
        Row: {
          event_date: string
          event_type: string
          exam_type_id: string
          id: string
          notes: string | null
          source_url: string | null
        }
        Insert: {
          event_date: string
          event_type: string
          exam_type_id: string
          id?: string
          notes?: string | null
          source_url?: string | null
        }
        Update: {
          event_date?: string
          event_type?: string
          exam_type_id?: string
          id?: string
          notes?: string | null
          source_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "exam_schedules_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      exam_types: {
        Row: {
          category_id: string
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          name: string
          official_registration_url: string | null
          phase: number
          slug: string
        }
        Insert: {
          category_id: string
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name: string
          official_registration_url?: string | null
          phase?: number
          slug: string
        }
        Update: {
          category_id?: string
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name?: string
          official_registration_url?: string | null
          phase?: number
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "exam_types_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "exam_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      flashcard_reviews: {
        Row: {
          created_at: string
          ease_factor: number
          flashcard_id: string
          interval_days: number
          last_reviewed_at: string | null
          next_review_at: string | null
          repetitions: number
          user_id: string
        }
        Insert: {
          created_at?: string
          ease_factor?: number
          flashcard_id: string
          interval_days?: number
          last_reviewed_at?: string | null
          next_review_at?: string | null
          repetitions?: number
          user_id: string
        }
        Update: {
          created_at?: string
          ease_factor?: number
          flashcard_id?: string
          interval_days?: number
          last_reviewed_at?: string | null
          next_review_at?: string | null
          repetitions?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "flashcard_reviews_flashcard_id_fkey"
            columns: ["flashcard_id"]
            isOneToOne: false
            referencedRelation: "flashcards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flashcard_reviews_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      flashcards: {
        Row: {
          back: string
          front: string
          id: string
          is_premium: boolean
          topic_id: string
        }
        Insert: {
          back: string
          front: string
          id?: string
          is_premium?: boolean
          topic_id: string
        }
        Update: {
          back?: string
          front?: string
          id?: string
          is_premium?: boolean
          topic_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "flashcards_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
        ]
      }
      mistake_logs: {
        Row: {
          id: string
          last_wrong_at: string
          mastered_at: string | null
          next_review_at: string | null
          question_id: string
          times_wrong: number
          user_id: string
          wrong_choice_id: string | null
        }
        Insert: {
          id?: string
          last_wrong_at?: string
          mastered_at?: string | null
          next_review_at?: string | null
          question_id: string
          times_wrong?: number
          user_id: string
          wrong_choice_id?: string | null
        }
        Update: {
          id?: string
          last_wrong_at?: string
          mastered_at?: string | null
          next_review_at?: string | null
          question_id?: string
          times_wrong?: number
          user_id?: string
          wrong_choice_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "mistake_logs_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mistake_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      mock_exam_questions: {
        Row: {
          mock_exam_id: string
          question_id: string
          sort_order: number
        }
        Insert: {
          mock_exam_id: string
          question_id: string
          sort_order: number
        }
        Update: {
          mock_exam_id?: string
          question_id?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "mock_exam_questions_mock_exam_id_fkey"
            columns: ["mock_exam_id"]
            isOneToOne: false
            referencedRelation: "mock_exams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mock_exam_questions_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      mock_exams: {
        Row: {
          blueprint_id: string | null
          duration_seconds: number
          exam_type_id: string
          id: string
          is_active: boolean
          item_count: number
          title: string
        }
        Insert: {
          blueprint_id?: string | null
          duration_seconds: number
          exam_type_id: string
          id?: string
          is_active?: boolean
          item_count: number
          title: string
        }
        Update: {
          blueprint_id?: string | null
          duration_seconds?: number
          exam_type_id?: string
          id?: string
          is_active?: boolean
          item_count?: number
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "mock_exams_blueprint_id_fkey"
            columns: ["blueprint_id"]
            isOneToOne: false
            referencedRelation: "exam_blueprints"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mock_exams_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_transactions: {
        Row: {
          amount_php: number
          created_at: string
          id: string
          product_id: string
          provider: Database["public"]["Enums"]["payment_provider"]
          raw_receipt: Json | null
          status: Database["public"]["Enums"]["payment_status"]
          store_transaction_id: string | null
          user_id: string
        }
        Insert: {
          amount_php: number
          created_at?: string
          id?: string
          product_id: string
          provider: Database["public"]["Enums"]["payment_provider"]
          raw_receipt?: Json | null
          status?: Database["public"]["Enums"]["payment_status"]
          store_transaction_id?: string | null
          user_id: string
        }
        Update: {
          amount_php?: number
          created_at?: string
          id?: string
          product_id?: string
          provider?: Database["public"]["Enums"]["payment_provider"]
          raw_receipt?: Json | null
          status?: Database["public"]["Enums"]["payment_status"]
          store_transaction_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_transactions_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "subscription_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payment_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      question_versions: {
        Row: {
          change_reason: string | null
          created_at: string
          created_by: string | null
          id: string
          question_id: string
          snapshot: Json
          version_number: number
        }
        Insert: {
          change_reason?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          question_id: string
          snapshot: Json
          version_number: number
        }
        Update: {
          change_reason?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          question_id?: string
          snapshot?: Json
          version_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "question_versions_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      questions: {
        Row: {
          blueprint_id: string | null
          choices: Json
          correct_choice_id: string
          created_at: string
          difficulty: number
          explanation_en: string | null
          explanation_fil: string | null
          id: string
          is_verified: boolean
          reviewed_at: string | null
          reviewed_by: string | null
          source: string | null
          source_note: string | null
          status: Database["public"]["Enums"]["question_status"]
          stem: string
          tags: string[] | null
          topic_id: string
          updated_at: string
        }
        Insert: {
          blueprint_id?: string | null
          choices: Json
          correct_choice_id: string
          created_at?: string
          difficulty?: number
          explanation_en?: string | null
          explanation_fil?: string | null
          id?: string
          is_verified?: boolean
          reviewed_at?: string | null
          reviewed_by?: string | null
          source?: string | null
          source_note?: string | null
          status?: Database["public"]["Enums"]["question_status"]
          stem: string
          tags?: string[] | null
          topic_id: string
          updated_at?: string
        }
        Update: {
          blueprint_id?: string | null
          choices?: Json
          correct_choice_id?: string
          created_at?: string
          difficulty?: number
          explanation_en?: string | null
          explanation_fil?: string | null
          id?: string
          is_verified?: boolean
          reviewed_at?: string | null
          reviewed_by?: string | null
          source?: string | null
          source_note?: string | null
          status?: Database["public"]["Enums"]["question_status"]
          stem?: string
          tags?: string[] | null
          topic_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "questions_blueprint_id_fkey"
            columns: ["blueprint_id"]
            isOneToOne: false
            referencedRelation: "exam_blueprints"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "questions_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_answers: {
        Row: {
          answered_at: string
          id: string
          is_correct: boolean | null
          question_id: string
          selected_choice_id: string | null
          session_id: string
          time_spent_seconds: number | null
        }
        Insert: {
          answered_at?: string
          id?: string
          is_correct?: boolean | null
          question_id: string
          selected_choice_id?: string | null
          session_id: string
          time_spent_seconds?: number | null
        }
        Update: {
          answered_at?: string
          id?: string
          is_correct?: boolean | null
          question_id?: string
          selected_choice_id?: string | null
          session_id?: string
          time_spent_seconds?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "quiz_answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_answers_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "quiz_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_sessions: {
        Row: {
          completed_at: string | null
          duration_seconds: number | null
          exam_type_id: string
          id: string
          item_count: number
          mock_exam_id: string | null
          mode: Database["public"]["Enums"]["quiz_mode"]
          score_percent: number | null
          started_at: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          duration_seconds?: number | null
          exam_type_id: string
          id?: string
          item_count: number
          mock_exam_id?: string | null
          mode: Database["public"]["Enums"]["quiz_mode"]
          score_percent?: number | null
          started_at?: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          duration_seconds?: number | null
          exam_type_id?: string
          id?: string
          item_count?: number
          mock_exam_id?: string | null
          mode?: Database["public"]["Enums"]["quiz_mode"]
          score_percent?: number | null
          started_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_sessions_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_sessions_mock_exam_id_fkey"
            columns: ["mock_exam_id"]
            isOneToOne: false
            referencedRelation: "mock_exams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      readiness_snapshots: {
        Row: {
          computed_at: string
          exam_type_id: string
          factors: Json
          id: string
          score_0_100: number
          user_id: string
        }
        Insert: {
          computed_at?: string
          exam_type_id: string
          factors?: Json
          id?: string
          score_0_100: number
          user_id: string
        }
        Update: {
          computed_at?: string
          exam_type_id?: string
          factors?: Json
          id?: string
          score_0_100?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "readiness_snapshots_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "readiness_snapshots_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      reported_questions: {
        Row: {
          created_at: string
          details: string | null
          id: string
          question_id: string
          reason: Database["public"]["Enums"]["report_reason"]
          resolved_at: string | null
          resolved_by: string | null
          status: Database["public"]["Enums"]["report_status"]
          user_id: string
        }
        Insert: {
          created_at?: string
          details?: string | null
          id?: string
          question_id: string
          reason: Database["public"]["Enums"]["report_reason"]
          resolved_at?: string | null
          resolved_by?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          user_id: string
        }
        Update: {
          created_at?: string
          details?: string | null
          id?: string
          question_id?: string
          reason?: Database["public"]["Enums"]["report_reason"]
          resolved_at?: string | null
          resolved_by?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reported_questions_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      review_materials: {
        Row: {
          body: string
          id: string
          is_premium: boolean
          material_type: string
          title: string
          topic_id: string
        }
        Insert: {
          body: string
          id?: string
          is_premium?: boolean
          material_type?: string
          title: string
          topic_id: string
        }
        Update: {
          body?: string
          id?: string
          is_premium?: boolean
          material_type?: string
          title?: string
          topic_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_materials_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
        ]
      }
      study_plans: {
        Row: {
          daily_minutes: number | null
          exam_type_id: string
          generated_at: string
          id: string
          is_active: boolean
          plan_json: Json
          source: Database["public"]["Enums"]["study_plan_source"]
          target_date: string | null
          user_id: string
        }
        Insert: {
          daily_minutes?: number | null
          exam_type_id: string
          generated_at?: string
          id?: string
          is_active?: boolean
          plan_json?: Json
          source?: Database["public"]["Enums"]["study_plan_source"]
          target_date?: string | null
          user_id: string
        }
        Update: {
          daily_minutes?: number | null
          exam_type_id?: string
          generated_at?: string
          id?: string
          is_active?: boolean
          plan_json?: Json
          source?: Database["public"]["Enums"]["study_plan_source"]
          target_date?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "study_plans_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "study_plans_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      subject_areas: {
        Row: {
          exam_type_id: string
          id: string
          name: string
          slug: string
          sort_order: number
          weight_percent: number | null
        }
        Insert: {
          exam_type_id: string
          id?: string
          name: string
          slug: string
          sort_order?: number
          weight_percent?: number | null
        }
        Update: {
          exam_type_id?: string
          id?: string
          name?: string
          slug?: string
          sort_order?: number
          weight_percent?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "subject_areas_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      subscription_products: {
        Row: {
          duration_days: number | null
          exam_type_id: string | null
          id: string
          price_php: number
          sku: string
          store: string
          tier: Database["public"]["Enums"]["subscription_tier"]
        }
        Insert: {
          duration_days?: number | null
          exam_type_id?: string | null
          id?: string
          price_php: number
          sku: string
          store?: string
          tier: Database["public"]["Enums"]["subscription_tier"]
        }
        Update: {
          duration_days?: number | null
          exam_type_id?: string | null
          id?: string
          price_php?: number
          sku?: string
          store?: string
          tier?: Database["public"]["Enums"]["subscription_tier"]
        }
        Relationships: [
          {
            foreignKeyName: "subscription_products_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
        ]
      }
      topic_mastery: {
        Row: {
          accuracy: number
          attempts: number
          correct_count: number
          ease_factor: number
          id: string
          interval_days: number
          last_seen_at: string | null
          next_review_at: string | null
          topic_id: string
          user_id: string
        }
        Insert: {
          accuracy?: number
          attempts?: number
          correct_count?: number
          ease_factor?: number
          id?: string
          interval_days?: number
          last_seen_at?: string | null
          next_review_at?: string | null
          topic_id: string
          user_id: string
        }
        Update: {
          accuracy?: number
          attempts?: number
          correct_count?: number
          ease_factor?: number
          id?: string
          interval_days?: number
          last_seen_at?: string | null
          next_review_at?: string | null
          topic_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "topic_mastery_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "topic_mastery_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      topics: {
        Row: {
          blueprint_topic_code: string | null
          description: string | null
          id: string
          name: string
          slug: string
          sort_order: number
          subject_area_id: string
        }
        Insert: {
          blueprint_topic_code?: string | null
          description?: string | null
          id?: string
          name: string
          slug: string
          sort_order?: number
          subject_area_id: string
        }
        Update: {
          blueprint_topic_code?: string | null
          description?: string | null
          id?: string
          name?: string
          slug?: string
          sort_order?: number
          subject_area_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "topics_subject_area_id_fkey"
            columns: ["subject_area_id"]
            isOneToOne: false
            referencedRelation: "subject_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      user_badges: {
        Row: {
          badge_id: string
          earned_at: string
          user_id: string
        }
        Insert: {
          badge_id: string
          earned_at?: string
          user_id: string
        }
        Update: {
          badge_id?: string
          earned_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_badges_badge_id_fkey"
            columns: ["badge_id"]
            isOneToOne: false
            referencedRelation: "achievement_badges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_badges_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_entitlements: {
        Row: {
          created_at: string
          exam_type_id: string | null
          expires_at: string | null
          id: string
          product_id: string
          source: string
          transaction_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          exam_type_id?: string | null
          expires_at?: string | null
          id?: string
          product_id: string
          source?: string
          transaction_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          exam_type_id?: string | null
          expires_at?: string | null
          id?: string
          product_id?: string
          source?: string
          transaction_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_entitlements_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_entitlements_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "subscription_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_entitlements_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_exam_goals: {
        Row: {
          created_at: string
          current_level: string
          daily_minutes: number
          exam_type_id: string
          id: string
          is_active: boolean
          major_slug: string | null
          onboarding_completed_at: string | null
          target_exam_date: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          current_level?: string
          daily_minutes?: number
          exam_type_id: string
          id?: string
          is_active?: boolean
          major_slug?: string | null
          onboarding_completed_at?: string | null
          target_exam_date?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          current_level?: string
          daily_minutes?: number
          exam_type_id?: string
          id?: string
          is_active?: boolean
          major_slug?: string | null
          onboarding_completed_at?: string | null
          target_exam_date?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_exam_goals_exam_type_id_fkey"
            columns: ["exam_type_id"]
            isOneToOne: false
            referencedRelation: "exam_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_exam_goals_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_preferences: {
        Row: {
          dark_mode: boolean
          exam_reminders_enabled: boolean
          explanation_locale: string
          notifications_enabled: boolean
          reminder_hour: number
          reminder_minute: number
          updated_at: string
          user_id: string
        }
        Insert: {
          dark_mode?: boolean
          exam_reminders_enabled?: boolean
          explanation_locale?: string
          notifications_enabled?: boolean
          reminder_hour?: number
          reminder_minute?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          dark_mode?: boolean
          exam_reminders_enabled?: boolean
          explanation_locale?: string
          notifications_enabled?: boolean
          reminder_hour?: number
          reminder_minute?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_push_tokens: {
        Row: {
          id: string
          platform: string
          token: string
          updated_at: string
          user_id: string
        }
        Insert: {
          id?: string
          platform: string
          token: string
          updated_at?: string
          user_id: string
        }
        Update: {
          id?: string
          platform?: string
          token?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          display_name: string | null
          email: string | null
          id: string
          locale: string
          role: Database["public"]["Enums"]["user_role"]
          streak_count: number
          streak_last_date: string | null
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          email?: string | null
          id: string
          locale?: string
          role?: Database["public"]["Enums"]["user_role"]
          streak_count?: number
          streak_last_date?: string | null
        }
        Update: {
          created_at?: string
          display_name?: string | null
          email?: string | null
          id?: string
          locale?: string
          role?: Database["public"]["Enums"]["user_role"]
          streak_count?: number
          streak_last_date?: string | null
        }
        Relationships: []
      }
      waitlist_signups: {
        Row: {
          created_at: string
          email: string
          exam_interest: string | null
          id: string
          platform: string | null
        }
        Insert: {
          created_at?: string
          email: string
          exam_interest?: string | null
          id?: string
          platform?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          exam_interest?: string | null
          id?: string
          platform?: string | null
        }
        Relationships: []
      }
      web_checkout_sessions: {
        Row: {
          amount_php: number
          created_at: string
          expires_at: string
          id: string
          paid_at: string | null
          product_id: string
          provider: Database["public"]["Enums"]["payment_provider"]
          reference_code: string
          source: string
          status: string
          submitted_at: string | null
          user_id: string
          utm_source: string | null
        }
        Insert: {
          amount_php: number
          created_at?: string
          expires_at?: string
          id?: string
          paid_at?: string | null
          product_id: string
          provider: Database["public"]["Enums"]["payment_provider"]
          reference_code: string
          source?: string
          status?: string
          submitted_at?: string | null
          user_id: string
          utm_source?: string | null
        }
        Update: {
          amount_php?: number
          created_at?: string
          expires_at?: string
          id?: string
          paid_at?: string | null
          product_id?: string
          provider?: Database["public"]["Enums"]["payment_provider"]
          reference_code?: string
          source?: string
          status?: string
          submitted_at?: string | null
          user_id?: string
          utm_source?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "web_checkout_sessions_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "subscription_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "web_checkout_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _generate_barkada_code: { Args: never; Returns: string }
      award_user_badges: { Args: { p_user_id?: string }; Returns: Json }
      check_question_answer: {
        Args: { p_choice_id: string; p_question_id: string }
        Returns: {
          correct_choice_id: string
          explanation_en: string
          explanation_fil: string
          is_correct: boolean
        }[]
      }
      complete_diagnostic: {
        Args: { p_duration_seconds: number; p_session_id: string }
        Returns: Json
      }
      complete_pasapath_task: {
        Args: { p_exam_slug: string; p_task_id: string }
        Returns: Json
      }
      complete_quiz_session: {
        Args: { p_duration_seconds: number; p_session_id: string }
        Returns: number
      }
      create_barkada_challenge: {
        Args: { p_group_id: string; p_question_count?: number }
        Returns: Json
      }
      create_barkada_group: {
        Args: { p_exam_slug: string; p_name?: string }
        Returns: Json
      }
      create_web_checkout_session: {
        Args: {
          p_provider: string
          p_sku: string
          p_source?: string
          p_utm_source?: string
        }
        Returns: Json
      }
      delete_user_account: { Args: never; Returns: undefined }
      fulfill_iap_purchase: {
        Args: {
          p_provider: Database["public"]["Enums"]["payment_provider"]
          p_raw_receipt?: Json
          p_sku: string
          p_transaction_id: string
          p_user_id: string
        }
        Returns: Json
      }
      fulfill_web_checkout: {
        Args: { p_auto_demo?: boolean; p_reference_code: string }
        Returns: Json
      }
      get_admin_dashboard_stats: { Args: never; Returns: Json }
      get_app_announcements: {
        Args: { p_exam_slug?: string; p_limit?: number }
        Returns: {
          body: string
          id: string
          published_at: string
          title: string
        }[]
      }
      get_bookmarked_materials: {
        Args: { p_exam_slug?: string }
        Returns: {
          body: string
          bookmarked_at: string
          material_id: string
          material_type: string
          subject_name: string
          title: string
          topic_name: string
        }[]
      }
      get_content_changelog: {
        Args: { p_exam_slug?: string; p_limit?: number }
        Returns: {
          body: string
          exam_slug: string
          id: string
          published_at: string
          title: string
        }[]
      }
      get_content_counts: { Args: { p_exam_slug: string }; Returns: Json }
      get_topic_question_counts: {
        Args: { p_exam_slug: string; p_subject_slug: string }
        Returns: { topic_slug: string; published_count: number }[]
      }
      get_diagnostic_questions: {
        Args: { p_exam_slug: string; p_limit?: number }
        Returns: {
          choices: Json
          difficulty: number
          exam_slug: string
          id: string
          stem: string
          subject_name: string
          topic_name: string
        }[]
      }
      get_due_flashcard_count: {
        Args: { p_exam_slug: string }
        Returns: number
      }
      get_due_flashcards: {
        Args: {
          p_exam_slug: string
          p_limit?: number
          p_subject_slug?: string
          p_topic_slug?: string
        }
        Returns: {
          back: string
          front: string
          id: string
          next_review_at: string
          repetitions: number
          subject_name: string
          topic_name: string
          topic_slug: string
        }[]
      }
      get_exam_schedules_by_exam: {
        Args: { p_exam_slug: string }
        Returns: {
          days_until: number
          event_date: string
          event_type: string
          id: string
          notes: string
          source_url: string
        }[]
      }
      get_exam_topic_analytics: {
        Args: { p_exam_slug: string }
        Returns: {
          accuracy: number
          attempts: number
          correct_count: number
          subject_name: string
          topic_id: string
          topic_name: string
          topic_slug: string
        }[]
      }
      get_latest_readiness: { Args: { p_exam_slug: string }; Returns: Json }
      get_leaderboard: {
        Args: { p_exam_slug: string; p_limit?: number; p_period?: string }
        Returns: {
          display_name: string
          is_current_user: boolean
          rank: number
          user_id: string
          xp: number
        }[]
      }
      get_mistake_bank: {
        Args: { p_days_back?: number; p_exam_slug: string; p_limit?: number }
        Returns: {
          id: string
          last_wrong_at: string
          next_review_at: string
          question_id: string
          stem: string
          subject_name: string
          times_wrong: number
          topic_name: string
        }[]
      }
      get_mock_exam_history: {
        Args: { p_exam_slug: string; p_limit?: number }
        Returns: {
          completed_at: string
          duration_seconds: number
          item_count: number
          mock_title: string
          passed: boolean
          score_percent: number
          session_id: string
        }[]
      }
      get_mock_exam_questions: {
        Args: { p_mock_exam_id: string }
        Returns: {
          choices: Json
          difficulty: number
          exam_slug: string
          id: string
          is_preview: boolean
          preview_limit: number
          sort_order: number
          stem: string
          subject_name: string
          topic_name: string
        }[]
      }
      get_my_barkada: { Args: { p_exam_slug: string }; Returns: Json }
      get_offline_pack_content: { Args: { p_exam_slug: string }; Returns: Json }
      get_pasapath_week: { Args: { p_exam_slug: string }; Returns: Json }
      get_pending_web_checkouts: {
        Args: { p_limit?: number }
        Returns: {
          amount_php: number
          created_at: string
          id: string
          provider: string
          reference_code: string
          sku: string
          source: string
          status: string
          submitted_at: string
          user_email: string
          utm_source: string
        }[]
      }
      get_practice_questions: {
        Args: { p_exam_slug: string; p_limit?: number; p_topic_slug?: string }
        Returns: {
          choices: Json
          difficulty: number
          exam_slug: string
          id: string
          stem: string
          subject_name: string
          topic_name: string
        }[]
      }
      get_question_for_staff: { Args: { p_question_id: string }; Returns: Json }
      get_questions_by_ids: {
        Args: { p_ids: string[] }
        Returns: {
          choices: Json
          difficulty: number
          exam_slug: string
          id: string
          stem: string
          subject_name: string
          topic_name: string
        }[]
      }
      get_readiness_history: {
        Args: { p_exam_slug: string; p_limit?: number }
        Returns: {
          computed_at: string
          score: number
        }[]
      }
      get_review_materials_by_exam:
        | {
            Args: { p_exam_slug: string }
            Returns: {
              body: string
              id: string
              is_premium: boolean
              material_type: string
              subject_name: string
              subject_slug: string
              title: string
              topic_name: string
              topic_slug: string
            }[]
          }
        | {
            Args: { p_exam_slug: string; p_material_type?: string }
            Returns: {
              body: string
              id: string
              is_premium: boolean
              material_type: string
              subject_name: string
              subject_slug: string
              title: string
              topic_name: string
              topic_slug: string
            }[]
          }
      get_session_review: {
        Args: { p_session_id: string }
        Returns: {
          choices: Json
          correct_choice_id: string
          explanation_en: string
          explanation_fil: string
          is_correct: boolean
          question_id: string
          selected_choice_id: string
          stem: string
          time_spent_seconds: number
        }[]
      }
      get_today_pasapath: { Args: { p_exam_slug: string }; Returns: Json }
      get_usage_limits: { Args: { p_exam_slug: string }; Returns: Json }
      get_user_badges: {
        Args: { p_user_id?: string }
        Returns: {
          description: string
          earned_at: string
          emoji: string
          slug: string
          title: string
        }[]
      }
      get_waitlist_signups: {
        Args: { p_limit?: number }
        Returns: {
          created_at: string
          email: string
          exam_interest: string
          id: string
          platform: string
        }[]
      }
      get_weak_area_questions: {
        Args: { p_exam_slug: string; p_limit?: number }
        Returns: {
          choices: Json
          difficulty: number
          exam_slug: string
          id: string
          stem: string
          subject_name: string
          topic_name: string
        }[]
      }
      get_web_checkout_status: {
        Args: { p_reference_code: string }
        Returns: Json
      }
      get_weekly_summary: { Args: { p_exam_slug: string }; Returns: Json }
      grant_demo_entitlement: {
        Args: { p_exam_type_id?: string; p_product_id: string }
        Returns: undefined
      }
      has_completed_diagnostic: {
        Args: { p_exam_slug: string }
        Returns: boolean
      }
      iap_product_is_subscription: { Args: { p_sku: string }; Returns: boolean }
      is_staff_user: { Args: never; Returns: boolean }
      join_barkada_group: { Args: { p_invite_code: string }; Returns: Json }
      patch_web_checkout_attribution: {
        Args: {
          p_reference_code: string
          p_source?: string
          p_utm_source?: string
        }
        Returns: Json
      }
      recompute_readiness_batch: { Args: { p_limit?: number }; Returns: Json }
      recompute_user_readiness: { Args: { p_exam_slug: string }; Returns: Json }
      recompute_user_readiness_for: {
        Args: { p_exam_slug: string; p_user_id: string }
        Returns: Json
      }
      resolve_reported_question: {
        Args: {
          p_notes?: string
          p_report_id: string
          p_status: Database["public"]["Enums"]["report_status"]
        }
        Returns: Json
      }
      review_flashcard: {
        Args: { p_flashcard_id: string; p_rating: number }
        Returns: Json
      }
      submit_barkada_challenge_result: {
        Args: {
          p_challenge_id: string
          p_correct_count: number
          p_score_percent: number
          p_session_id: string
          p_total_count: number
        }
        Returns: Json
      }
      update_question_staff: {
        Args: {
          p_explanation_en?: string
          p_explanation_fil?: string
          p_question_id: string
          p_status?: Database["public"]["Enums"]["question_status"]
          p_stem?: string
        }
        Returns: Json
      }
      update_topic_mastery: {
        Args: { p_is_correct: boolean; p_question_id: string }
        Returns: undefined
      }
      upsert_mistake_log: {
        Args: { p_question_id: string; p_wrong_choice_id: string }
        Returns: undefined
      }
      user_has_content_access: {
        Args: { p_exam_type_id: string }
        Returns: boolean
      }
    }
    Enums: {
      payment_provider: "apple" | "google" | "gcash" | "maya"
      payment_status: "pending" | "completed" | "refunded"
      question_status: "draft" | "in_review" | "published" | "archived"
      quiz_mode:
        | "practice"
        | "timed"
        | "mock"
        | "diagnostic"
        | "mistake_review"
        | "weak_area"
        | "barkada"
        | "board"
      report_reason:
        | "wrong_answer"
        | "unclear_question"
        | "outdated"
        | "typo"
        | "other"
      report_status: "open" | "triaged" | "fixed" | "rejected"
      study_plan_source: "template" | "ai_generated" | "pasapath_engine"
      subscription_tier: "free" | "exam_pass" | "plus"
      user_role: "student" | "admin" | "content_reviewer" | "content_author"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      payment_provider: ["apple", "google", "gcash", "maya"],
      payment_status: ["pending", "completed", "refunded"],
      question_status: ["draft", "in_review", "published", "archived"],
      quiz_mode: [
        "practice",
        "timed",
        "mock",
        "diagnostic",
        "mistake_review",
        "weak_area",
        "barkada",
        "board",
      ],
      report_reason: [
        "wrong_answer",
        "unclear_question",
        "outdated",
        "typo",
        "other",
      ],
      report_status: ["open", "triaged", "fixed", "rejected"],
      study_plan_source: ["template", "ai_generated", "pasapath_engine"],
      subscription_tier: ["free", "exam_pass", "plus"],
      user_role: ["student", "admin", "content_reviewer", "content_author"],
    },
  },
} as const
