/**
 * Flashcard Batch D: Filipino Vocab (20 Pro + 15 Sub), Filipino Grammar (20 Pro + 11 Sub),
 * Filipino Reading/Paragraph (14 Pro + 9 Sub), Spelling (26 Sub), Paragraph Org (15 Pro + 14 Sub)
 */
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
const env = Object.fromEntries(
  readFileSync('/Users/lyndon/reviewnatin/.env.supabase','utf8')
    .split('\n').filter(l=>l&&!l.startsWith('#'))
    .map(l=>[l.split('=')[0].trim(),l.slice(l.indexOf('=')+1).trim()])
);
const sb = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const T = {
  PRO_vocab_fil:    'c2808ba1-5ba9-449c-afbf-a4dbd1d248dd',
  SUB_vocab_fil:    'e4856eb1-2eaf-45e7-92b3-85953623a847',
  PRO_grammar_fil:  'd3b160b3-f0e1-4fd4-a9d8-c8dcbc401c79',
  SUB_grammar_fil:  'd6e97a36-5e2f-4a98-a363-abefdcf7ab62',
  PRO_reading_fil:  '43399734-967c-444c-b583-b68fdff2de1c',
  SUB_reading_fil:  '679fffb1-c0ca-46e8-93e2-f0c35874b960',
  PRO_para_fil:     '867c0551-9aa4-4dad-a4fc-bc8d8d6eada4',
  SUB_para_fil:     '9b226eb5-beb6-41ac-b92e-b666294126a3',
  PRO_para_org:     '0e22fcfd-195f-475c-8df5-5584e229cbee',
  SUB_para_org:     '539b1777-4f5d-40a8-8a04-703038f1653a',
  SUB_spelling:     '55bc7cff-808b-48b7-97cb-1cb93ca1e5ee',
};
const f = (t, fr, bk) => ({ topic_id:t, front:fr, back:bk, is_premium:false });

// ── FILIPINO VOCABULARY (20 new Pro, 15 new Sub) ──────────────────────────────
const filVocab = [
  // Pro
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MAPANLINLANG','Kasingkahulugan: mapandaya, mapaglinlang, tuso, magdaraya, manlilinlang.\nKasalungat: tapat, matuwid, mapagkakatiwalaan, honest.\nHalimbawa: "Ang mapanlinlang na negosyante ay nagbenta ng pekeng produkto."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KASIPAGAN','Kasingkahulugan: kasipagan = pagiging masipag; sinonimo: katiyagaan, kasipagan, kasigasigan, kakayahang magtrabaho.\nKasalungat: katamaran, pagkukulang, pagpapabaya.\nHalimbawa: "Ang kasipagan ng mga manggagawa ay nagpaunlad ng industriya."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng PAGMAMAHAL (sa bayan)','Kasingkahulugan: pagmamahal sa bayan = pagkamakabayan; sinonimo: nasyonalismo, pagpapahalaga sa sariling bansa, katapatan sa bayan.\nKasalungat: pagtataksil sa bayan, kakulangan ng pagkamakabayan.\nHalimbawa: "Ipinakita ni Rizal ang kanyang pagmamahal sa bayan sa pamamagitan ng kanyang mga sulatin."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KATAPATAN (sa trabaho)','Kasingkahulugan: katapatan sa trabaho = dedikasyon; sinonimo: pagtatapat, pagiging tapat, integridad, katibayan.\nKasalungat: kawalang-katapatan, pagtataksil, pabaya, di-mapagkakatiwalaan.\nHalimbawa: "Ang katapatan ng isang kawani sa kanyang tungkulin ay mahalagang katangian."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KAHALAGAHAN','Kasingkahulugan: kahalagahan = halaga; sinonimo: kabutihan, kapaki-pakinabang, kakayahang magbigay ng benepisyo.\nKasalungat: kawalang-halaga, walang silbi, walang kabuluhan.\nHalimbawa: "Ang kahalagahan ng edukasyon ay nasusukat sa pag-unlad ng isang tao."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MAGALANG','Kasingkahulugan: magalang = polite; sinonimo: may pitagan, mapagpitagan, mahinhin, maayos ang ugali.\nKasalungat: bastos, walang galang, walang pitagan, mahalay, mapanghamak.\nHalimbawa: "Ang magalang na opisyal ay tinatanggap ng mabuti ng mga mamamayan."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MABILIS (kilos)','Kasingkahulugan: mabilis = matulin; sinonimo: maliksi, maagap, mabisa, mabisa.\nKasalungat: mabagal, pabaya, matagal, mahirap kumilos.\nHalimbawa: "Ang mabilis na pagresponde ng mga tagapagligtas ay nakatulong sa mga biktima."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MAGITING','Kasingkahulugan: magiting = matapang; sinonimo: mahal ang puri, bayani, may lakas ng loob.\nKasalungat: duwag, walang tapang, takot, marupok.\nHalimbawa: "Ang mga magiting na sundalo ay hindi nagpatalo kahit sa harap ng panganib."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MAPAGBIGAY','Kasingkahulugan: mapagbigay = generous; sinonimo: bukas-palad, maalwan sa bigay, maawain, mabuting-kalooban.\nKasalungat: kuripot, imbi, makasarili, walang habag.\nHalimbawa: "Ang mapagbigay na donador ay tumulong sa mga mahihirap na estudyante."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MATALINO','Kasingkahulugan: matalino = wise; sinonimo: marunong, maalam, bihasa, matalisik, may karunungan.\nKasalungat: mangmang, ignorante, bobo, walang alam.\nHalimbawa: "Ang matalinong lider ay naghahanap ng pinakamainam na solusyon bago kumilos."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MAHINAHON','Kasingkahulugan: mahinahon = calm; sinonimo: tahimik, payapa, walang pagkagalit, may pagtitiis.\nKasalungat: mainit ang ulo, magagalitin, mapusok, walang pasensya.\nHalimbawa: "Ang mahinahong pinuno ay epektibo sa pamamahala ng krisis."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng MAPAGKUMBABA','Kasingkahulugan: mapagkumbaba = humble; sinonimo: hindi mapagmataas, simpleng ugali, walang kayabangan.\nKasalungat: mayabang, hambog, palalo, mapagmataas.\nHalimbawa: "Ang mapagkumbabang lider ay nakikinig sa mga mungkahi ng kanyang mga nasasakupan."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KATIYAKAN','Kasingkahulugan: katiyakan = certainty; sinonimo: kasiguruhan, katibayan, positibidad, pagiging sigurado.\nKasalungat: kawalan ng katiyakan, alinlangan, pagdududa.\nHalimbawa: "Ang katiyakan ng resulta ng halalan ay mahalaga para sa katatagan ng bansa."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KAPABAYAAN','Kasingkahulugan: kapabayaan = negligence; sinonimo: katamaran, kawalang-pakialam, hindi pag-iingat.\nKasalungat: kasipagan, pagiging maingat, responsibilidad, pag-iingat.\nHalimbawa: "Ang kapabayaan ng mga opisyal ay humantong sa pagkawala ng pondo."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KALINISAN','Kasingkahulugan: kalinisan = cleanliness; sinonimo: kaayusan, kadalisayan, kalinawan, pagiging malinis.\nKasalungat: karumihan, kadungisan, kahalumigmigan, kalaswan.\nHalimbawa: "Ang kalinisan ng opisina ay nagpapabuti ng kalusugan at produktibidad ng mga kawani."'),
  f(T.PRO_vocab_fil,'Kawikaan/Idiom: "Ang hindi marunong lumingon sa pinanggalingan ay hindi makararating sa paroroonan."','Kahulugan: Ang taong walang pagkilala sa kanyang kasaysayan at pinagmulan ay hindi makakaranas ng tunay na tagumpay. Dapat nating pahalagahan ang ating nakaraan upang mabuo ang magandang kinabukasan.\nGinamit sa: sikolohikal na pag-aaral, kasaysayan, pagkilala sa mga ninuno.'),
  f(T.PRO_vocab_fil,'Kawikaan/Idiom: "Aanhin pa ang damo kung patay na ang kabayo?"','Kahulugan: Walang silbi ang isang bagay kung wala na ang pangunahing kailangan nito. Ang huli ay hindi na makakatulong kung lumipas na ang pagkakataon.\nKatumbas na Ingles: "It\'s too late to shut the stable door after the horse has bolted." / "Crying over spilled milk."'),
  f(T.PRO_vocab_fil,'Kawikaan: "Sa ikauunlad ng bayan, disiplina ang kailangan."','Kahulugan: Ang tunay na pag-unlad ng isang bansa ay nangangailangan ng disiplina sa bawat mamamayan. Walang pag-unlad kung walang pagkakaisang kumilos ayon sa mga tuntunin at alituntunin.\nGamit: Pangkaraniwang islogan sa gobyerno, paaralan, at mga programa ng sibiko.'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng PAGIGING MAKATAO','Kasingkahulugan: pagiging makatao = humanity; sinonimo: pagkamaawain, malasakit sa kapwa, pagpapahalaga sa tao.\nKasalungat: kalupitan, kawalang-habag, pagwawalang-bahala sa kapwa.\nHalimbawa: "Ang pagiging makatao ng guro ay nararamdaman ng bawat estudyante."'),
  f(T.PRO_vocab_fil,'Kasingkahulugan at kasalungat ng KATUNAYAN','Kasingkahulugan: katunayan = truth, proof; sinonimo: katotohanan, ebidensya, patunay, katibayan.\nKasalungat: kasinungalingan, pagkukunwari, panloloko, di-katotohanan.\nHalimbawa: "Ang katunayan ng kaso ay ipinakita sa pamamagitan ng mga ebidensya sa korte."'),
  // Sub
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MABAIT','Kasingkahulugan: magandang-loob, maawain, mapagmalasakit, malambing.\nKasalungat: masamang-loob, malupit, walang awa.\nHalimbawa: "Ang mabait na kapitbahay ay laging handang tumulong."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MASAYA','Kasingkahulugan: maligaya, masasaya, masayahin, matuwa.\nKasalungat: malungkot, mapanglaw, nalulumbay, nagdadalamhati.\nHalimbawa: "Masaya ang bata nang matanggap niya ang kanyang regalo."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MABILIS','Kasingkahulugan: matulin, maliksi, maagap, madali.\nKasalungat: mabagal, mapagpaliban, walang pagmamadali.\nHalimbawa: "Mabilis na tumugon ang mga pulis sa tawag ng tulong."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MATAPANG','Kasingkahulugan: magiting, may lakas ng loob, walang takot, matatag.\nKasalungat: duwag, mahina ang loob, matakutin, marupok.\nHalimbawa: "Matapang na hinarap ng estudyante ang mahirap na pagsusulit."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MAHIRAP (buhay)','Kasingkahulugan: maralita, walang-wala, kulang-palad, salat.\nKasalungat: mayaman, mariwasa, maginhawa ang buhay, sagana.\nHalimbawa: "Ang mahirap na pamilya ay nakatanggap ng tulong mula sa pamahalaan."'),
  f(T.SUB_vocab_fil,'Kawikaan: "Ang taong nagigipit, kahit sa patalim ay kakapit."','Kahulugan: Kapag desperado ang isang tao, gagawa siya ng anumang bagay kahit mapanganib para makaligtas sa kanyang sitwasyon.\nGamit: Pag-unawa sa mga nagagawa ng tao sa krisis.'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MAHAL (pagmamahal)','Kasingkahulugan: pagmamahal, malasakit, kalinga, pagpapahalaga.\nKasalungat: pagkapoot, poot, pagkamaldita, kawalang-malasakit.\nHalimbawa: "Ang pagmamahal ng magulang ay walang katulad."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MAGANDA','Kasingkahulugan: marikit, kahali-halina, kaaya-aya, kaakit-akit.\nKasalungat: pangit, hindi kapuri-puri, nakakainis, walang ganda.\nHalimbawa: "Maganda ang tanawin sa bundok tuwing umaga."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MARUNONG','Kasingkahulugan: matalino, bihasa, may kaalaman, dalubhasa.\nKasalungat: mangmang, ignorante, walang alam, bobo.\nHalimbawa: "Marunong ang doktor sa kanyang larangan ng medisina."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MATANDA (gulang)','Kasingkahulugan: may gulang na, may edad, nakaranas na, beterano.\nKasalungat: bata, kabataan, batang-bata, wala pang gulang.\nHalimbawa: "Ang matandang guro ay may malawak na karanasan sa pagtuturo."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng TAHIMIK','Kasingkahulugan: payapa, walang ingay, mapayapa, mahinahon.\nKasalungat: maingay, malikot, walang kapayapaan, abala.\nHalimbawa: "Tahimik ang silid-aralan habang sinasagot ng mga estudyante ang pagsusulit."'),
  f(T.SUB_vocab_fil,'Kawikaan: "Huwag magbilang ng sisiw na hindi pa napipisa."','Kahulugan: Huwag umasa sa isang bagay na hindi pa sigurado. Baka hindi mangyari ang iyong inaasahan.\nKatumbas na Ingles: "Don\'t count your chickens before they hatch."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng MAINGAT','Kasingkahulugan: maingat = careful; sinonimo: maselang, mapansin, mapag-ingat, tiyak sa bawat hakbang.\nKasalungat: pabaya, walang ingat, basta-basta, di-maingat.\nHalimbawa: "Maingat na sinuri ng auditor ang mga rekord ng opisina."'),
  f(T.SUB_vocab_fil,'Kawikaan: "Kapag may tiyaga, may nilaga."','Kahulugan: Kapag may pasensya at pagtitiyaga, siguradong makakamit ang layunin. Ang tagumpay ay bunga ng patuloy na pagsisikap.\nKatumbas na Ingles: "Patience is a virtue." / "Where there\'s a will, there\'s a way."'),
  f(T.SUB_vocab_fil,'Kasingkahulugan at kasalungat ng TAPAT','Kasingkahulugan: tapat = honest, faithful; sinonimo: matuwid, totoo, hindi sinungaling, mapagkakatiwalaan.\nKasalungat: sinungaling, mapaglinlang, taksil, di-tapat.\nHalimbawa: "Tapat ang kawani sa kanyang opisina at hindi kumukuha ng hindi niya pag-aari."'),
];

// ── FILIPINO GRAMMAR (20 new Pro, 11 new Sub) ─────────────────────────────────
const filGrammar = [
  // Pro
  f(T.PRO_grammar_fil,'Wastong gamit: "Maaari" at "Puwede"','Parehong nagpapahiwatig ng posibilidad o pahintulot.\n"MAAARI" — mas pormal; ginagamit sa mga opisyal na dokumento at sa maingat na pagsulat.\n"PUWEDE" — mas impormal; ginagamit sa pang-araw-araw na pakikipag-usap.\nHalimbawa: "Maaari po bang makausap ang punong-guro?" (pormal)\n"Puwede ba akong lumabas?" (impormal)'),
  f(T.PRO_grammar_fil,'Wastong gamit: "Saka" at "Pagkatapos"','"SAKA" — ginagamit upang ipakilala ang kasunod na pangyayari; katulad ng "pagkatapos" ngunit mas maikli.\n"PAGKATAPOS" — mas pormal at espesipiko na nagpapahiwatig ng sunud-sunod na mga gawain.\nHalimbawa: "Kumain siya, saka natulog." (mas impormal)\n"Pagkatapos kumain, natulog siya." (mas pormal)\nSa pormal na sulatin, mas angkop ang "pagkatapos."'),
  f(T.PRO_grammar_fil,'Pagkilala sa mali: "Pumunta si Maria sa tindahan ng pagkain."','Walang pagkakamali. Ito ay isang payak na pangungusap na may wastong kayarian.\nPaksa: Si Maria\nPandiwa: Pumunta\nLagyan ng kilos: sa tindahan ng pagkain\n\nKomparasyon na may pagkakamali: "Pumunta ang Maria ng tindahan sa pagkain." (Mali — "ng tindahan" at "sa pagkain" ay hindi angkop na gamit ng mga pang-ukol.)'),
  f(T.PRO_grammar_fil,'Wastong gamit ng "naman" at "naman talaga"','"NAMAN" — nagpapahayag ng kaibahan, karagdagan, o pagbabago ng paksa.\nHalimbawa: "Mabait si Pedro. Masipag naman si Maria." (nagpapalitan ng paksa)\n"NAMAN TALAGA" — nagbibigay-diin sa sinabi; nagpapakita ng pagkabigo o pagkagulat.\nHalimbawa: "Ano naman talaga ang ginawa mo?" (may diin ng pagkabigo)'),
  f(T.PRO_grammar_fil,'Pokus ng pandiwa: Ano ang "pokus na aktor" (actor focus)?','POKUS NA AKTOR (Actor Focus): Ang paksa ng pangungusap ay ang gumagawa ng kilos.\nAng pandiwa ay nasa anyo ng um- (kumain, lumakad) o mag- (magluto, magtrabaho).\nHalimbawa: "KUMAIN ang bata ng kanin." → Ang bata (ang kumakain) ang paksa.\nEstruktura: Pandiwa (um-/mag-) + ang PAKSA + ng/sa + iba pang bahagi.'),
  f(T.PRO_grammar_fil,'Pokus ng pandiwa: Ano ang "pokus na layon" (object focus)?','POKUS NA LAYON (Object Focus): Ang paksa ng pangungusap ay ang tinatanggap ng kilos.\nAng pandiwa ay nasa anyo ng -in (kainin, basahin) o i- (itapon, ibigay).\nHalimbawa: "KINAIN ng bata ang kanin." → Ang kanin (ang kinakain) ang paksa.\nEstruktura: Pandiwa (-in/i-) + ng TAGAKILOS + ang PAKSA.'),
  f(T.PRO_grammar_fil,'Pokus ng pandiwa: "Pokus na benepisyaryo" (beneficiary focus)','POKUS NA BENEPISYARYO: Ang paksa ay ang taong nakikinabang o tinutugunan ng kilos.\nAng pandiwa ay ginagamit ang i- o ipag- na may kaugnay na anyo.\nHalimbawa: "INIHANDA ni Ana ang pagkain para sa bata." → "INIHANDA" = pinakinabangan ng bata.\nAng bata ang paksa sa pokus na benepisyaryo: "INIHANDA ni Ana para sa BATA ang pagkain."'),
  f(T.PRO_grammar_fil,'Wastong bantas: Paggamit ng kuwit (,) sa pagtatalaan','Ang KUWIT (,) ay ginagamit sa pagtatalaan ng tatlo o higit pang mga bagay o ideya.\nHalimbawa: "Ang mga pangunahing nutriyente ay protina, karbohidrat, at taba."\nPanuntuan: Lagyan ng kuwit bago ang pang-ugnay na "at" o "o" kung tatlo o higit pang mga aytem ang nakalista (serial comma).\nSa Filipino: "Pumunta sila sa Maynila, Cebu, at Davao."'),
  f(T.PRO_grammar_fil,'Wastong bantas: Paggamit ng panipi ("...") sa sipi ng salita','Ang PANIPI (") ay ginagamit upang ipakilala ang: (1) tuwirang sinabi ng isang tao, (2) pamagat ng tula, maikling kwento, o artikulo, (3) salita na nangangailangan ng espesyal na pagbibigay-diin.\nHalimbawa: "Sinabi ni Rizal, \'Ang kabataan ang pag-asa ng bayan.\'" (Direktang sipi)\nPamagat: "Noli Me Tangere" (nobela)'),
  f(T.PRO_grammar_fil,'Wastong gamit ng "kundi" at "kaya"','"KUNDI" — ginagamit upang ipahiwatig ng kaibahan o pagwawasto; katulad ng "but rather" sa Ingles.\nHalimbawa: "Hindi siya umalis, KUNDI siya ay nanatili."\n"KAYA" — nagpapahayag ng resulta o epekto; katulad ng "so/therefore".\nHalimbawa: "Maagang nagising siya, KAYA naabutan niya ang unang bus."'),
  f(T.PRO_grammar_fil,'Wastong gamit: "Sino" at "Alin"','"SINO" — tanong tungkol sa TAO.\nHalimbawa: "SINO ang dumating?" "SINO ang guro mo?"\n"ALIN" — tanong tungkol sa BAGAY o PAGPIPILIAN.\nHalimbawa: "ALIN ang gusto mo, kape o tsa?" "ALIN sa mga pagpipilian ang tamang sagot?"\nKomparasyon sa Ingles: SINO = who; ALIN = which.'),
  f(T.PRO_grammar_fil,'Kayarian ng pangungusap: Payak, Tambalan, Hugnayan','PAYAK — isang sugnay lamang (simple sentence).\n"Bumasa ang guro."\nTAMBALAN — dalawa o higit pang payak na pangungusap na magkasamang sugnay (compound sentence).\n"Bumasa ang guro at nagsulat ang mag-aaral."\nHUGNAYAN — may pangunahing at pangalawang sugnay (complex sentence).\n"Dahil maagang dumating ang guro, nagsimula agad ang klase."'),
  f(T.PRO_grammar_fil,'Wastong gamit ng pang-angkop: "-ng" at "na"','Pang-angkop ay nag-uugnay ng: pangngalan + pang-uri, pandiwa + pang-abay, atbp.\n"-NG" — idinudugtong sa salitang NAGTATAPOS sa PATINIG (a,e,i,o,u) o "w" at "y".\nHalimbawa: "maganda + -ng" = "magandang babae"\n"NA" — ginagamit pagkatapos ng salitang NAGTATAPOS sa KATINIG.\nHalimbawa: "matalim na espada"'),
  f(T.PRO_grammar_fil,'Pagkilala sa mali: "Ito ang libro na binasa ko ito."','Pagkakamali: "ito" ay inulit — "libro na binasa ko ITO." Ang "ito" sa dulo ay hindi na kailangan.\nWasto: "Ito ang librong binasa ko." o "Ito ang libro na binasa ko."\nPanuntunan: Sa panahunan ng sugnay, ang pang-ugnay (na, na+ng) ay gumaganap bilang kinatawan ng paksa — hindi na dapat ulitin ang panghalip.'),
  f(T.PRO_grammar_fil,'Wastong gamit: "Habang" at "Samantalang"','Parehong nagpapahiwatig ng dalawang bagay na nagaganap nang sabay.\n"HABANG" — ginagamit para sa dalawang bagay na sabay na nagaganap sa iisang panahon.\nHalimbawa: "Habang nagluluto siya, nagbabasa ang kanyang asawa."\n"SAMANTALANG" — mas madalas na nagpapahiwatig ng kaibahan o kontrasto sa pagitan ng dalawang pangyayari.\nHalimbawa: "Samantalang nagtatrabaho ang mga manlalabas, nagpapahinga ang iba."'),
  f(T.PRO_grammar_fil,'Wastong gamit ng "at" bilang pang-ugnay','Ang "AT" ay pang-ugnay na nagdudugtong ng dalawa o higit pang mga salita, parirala, o sugnay na may parehong grado.\nHalimbawa: "Matalino AT masipag si Pedro."\nKayarian: "Kumain, uminom, AT natulog siya."\nKagalingan: Gamitin ang kuwit (+at) sa pagtatalaan ng tatlo o higit pang mga bagay.'),
  f(T.PRO_grammar_fil,'Ano ang "Pandiwang di-tuwirang layon" (intransitive verb)?','PANDIWANG DI-TUWIRANG LAYON (intransitive): Hindi nangangailangan ng layon. Ang kilos ay tapos sa paksa.\nHalimbawa: "Lumuha si Maria." "Tumatawid ang bata." "Sumisigaw ang lalaki."\nKompara sa PANDIWANG MAY LAYON (transitive): "Kinain ng bata ang tinapay." (tinapay = layon)\nParaan ng pagkilala: Kung ang kilos ay may natanggap/tinatanggap na bagay → transitive.'),
  f(T.PRO_grammar_fil,'Paggamit ng Gitling (-) sa mga salitang Filipino','Ginagamit ang GITLING (-) sa:\n1. Mga salitang inuulit (reduplication): mabilis-mabilis, dahan-dahan, bago-bago.\n2. Mga salitang may unlapi na nagtatapos sa katinig + salitang nagsisimula sa katinig: pag-aralan, mag-aral.\n3. Mga numero na isinusulat: dalawampu\'t-isa, tatlumpu\'t-lima.\n4. Mga tambalang salita: ama-anak, magulang-anak.'),
  f(T.PRO_grammar_fil,'Paggamit ng "Ng" (marker) para sa mga pangngalan','Ang "NG" ay marker ng: (1) tagatanggap ng kilos sa pokus ng aktor;\n(2) nagmamay-ari;\n(3) katumbas ng "of" sa Ingles.\nHalimbawa: "Kinain ng bata ang mansanas." (bata = tagatanggap ng kilos)\n"Bahay ng lolo" (pagmamay-ari)\n"Lapis ng bata" (ng = "of the child")\nIba-iba ang gamit ng "ng" depende sa konteksto ng pangungusap.'),
  f(T.PRO_grammar_fil,'Wastong gamit: "Upang" at "Para sa/para"','"UPANG" — nagpapahiwatig ng layunin; ginagamit sa pormal na wika; katulad ng "in order to."\nHalimbawa: "Nag-aral siya nang husto UPANG pumasa sa pagsusulit."\n"PARA" / "PARA SA" — ginagamit sa impormal na wika para sa layunin; "para sa" ay para sa benepisyaryo.\nHalimbawa: "Nagtatrabaho siya para bumalik ang pamilya." (layunin)\n"Ito ay para sa iyo." (benepisyaryo)'),
  // Sub
  f(T.SUB_grammar_fil,'Wastong gamit ng "ng" at "nang" sa simpleng pangungusap','"NG" — nagpapakita ng pagmamay-ari o nagsisilbing kataga.\nHalimbawa: "Aklat NG guro" / "Kumain NG isda ang bata."\n"NANG" — nagpapahiwatig ng paraan o oras; katulad ng "when" o "in order to."\nHalimbawa: "NANG dumating siya..." (when) / "Tumakbo NANG mabilis." (paano)\nMnemonic: kung maaaring palitan ng "when" → "nang." Kung maaaring palitan ng "of/by" → "ng."'),
  f(T.SUB_grammar_fil,'Wastong gamit ng "daw" at "raw"','"DAW" — pagkatapos ng katinig.\nHalimbawa: "Matalino DAW ang bagong estudyante." (matalino ends in vowel "o"... wait — "o" is vowel. Actually: matalino ends in "o" (vowel) → should use "RAW")\nKunin ang huling LETRA: patinig → RAW; katinig → DAW.\nHalimbawa (tama): "Mabilis RAW siya." (mabilis ends in "s" — katinig → DAW)\nHalimbawa: "Maganda RAW ang palabas." (maganda ends in "a" — patinig → RAW)'),
  f(T.SUB_grammar_fil,'Wastong gamit ng "din" at "rin"','"DIN" — ginagamit pagkatapos ng salitang nagtatapos sa KATINIG.\nHalimbawa: "Pumunta DIN si Pedro."\n"RIN" — ginagamit pagkatapos ng salitang nagtatapos sa PATINIG.\nHalimbawa: "Pumunta RIN siya."\nMnemonic: Katinig → DiN. Patinig → RiN. Ang "d" at "r" ang nagbabago.'),
  f(T.SUB_grammar_fil,'Mga uri ng pangungusap ayon sa layunin','1. PANGUNGUSAP NA NAGSASALAYSAY — nagbibigay ng impormasyon. Wakas: tuldok (.).\n"Bukas ang paaralan."\n2. TANONG — nagtatanong. Wakas: tandang pananong (?)\n"Bukas ba ang paaralan?"\n3. UTOS — nag-uutos o humihiling. Wakas: tuldok o tandang padamdam.\n"Buksan ang paaralan."\n4. PADAMDAM — nagpapakita ng damdamin. Wakas: tandang padamdam (!)\n"Bukas na ang paaralan!"'),
  f(T.SUB_grammar_fil,'Pagkilala sa mali: "Natulog si Juan dahil kaya siya ay pagod."','Pagkakamali: "Dahil" at "kaya" ay magkaibang pang-ugnay na may parehong gamit — hindi sila magagamit nang sabay.\nWasto: "Natulog si Juan DAHIL pagod siya." o "Pagod si Juan, KAYA natulog siya."\nPanuntunan: Huwag gamitin ang "dahil" at "kaya" sa iisang pangungusap para sa parehong relasyon.'),
  f(T.SUB_grammar_fil,'Ano ang pang-abay at paano ito ginagamit?','PANG-ABAY — nagbibigay karagdagang impormasyon tungkol sa pandiwa, pang-uri, o ibang pang-abay.\nUri ng pang-abay:\n1. Pang-abay ng PAMALAGIAN (always, sometimes): lagi, madalas, minsan.\n2. Pang-abay ng PARAAN (how): mabilis, maingat, tahimik.\n3. Pang-abay ng DAMI (how much): lubos, bahagya, ganap.\nHalimbawa: "Mabilis siyang tumakbo." (mabilis = pang-abay na paraan)'),
  f(T.SUB_grammar_fil,'Wastong pagbaybay: Ang pagbaybay ng "NG" bilang salitang ginagamit sa pangungusap','Ang "NG" bilang salitang marker ay binibigkas at binabaybay bilang "NG" (isang pantig).\nIba sa "ANG" (marker ng paksa): "Kumain ANG bata."\n"NG" = marker ng layon/tagakilos: "Kumain NG mansanas ang bata."\nKaraniwan ding nakasulat: "Bahay NG tao" (ng = possessive marker: "the person\'s house").'),
  f(T.SUB_grammar_fil,'Wastong gamit: Ang tamang aspekto ng pandiwa','Aspekto ng pandiwa sa Filipino:\n1. KONTEMPLATIBO (hindi pa nagawa): mag-aaral, kakain.\n2. IMPERPEKTIBO (nagsimula na, hindi pa tapos): nag-aaral, kumakain.\n3. PERFEKTIBO (tapos na): nag-aral, kumain.\nHalimbawa: "Mag-aaral si Juan bukas." (kontemplatibo — hindi pa)\n"Nag-aaral si Juan ngayon." (imperpektibo — kasalukuyan)\n"Nag-aral si Juan kahapon." (perfektibo — tapos na)'),
  f(T.SUB_grammar_fil,'Pagkilala sa mali: "Ang mga bata ay maingay-ingay ang mga ito."','Pagkakamali: "Ang mga bata" at "ang mga ito" ay magkaparehong paksa — paulit-ulit.\nWasto: "Ang mga bata ay maingay-ingay." o "Maingay-ingay ang mga bata."\nPanuntunan: Huwag ulitin ang paksa sa pamamagitan ng panghalip kung ito ay malinaw na.'),
  f(T.SUB_grammar_fil,'Paggamit ng tandang pananong (?) sa Filipino','Ginagamit ang TANDANG PANANONG (?) sa katapusan ng TANONG na pangungusap.\nHalimbawa: "Kailan ka darating?"\n"Pumunta ka ba sa palengke?"\nMga salitang pananong: sino, ano, saan, kailan, paano, bakit, ilan, alin.\nMga pangungusap na pananong: nagtatapon ng tuldok at naglalagay ng tandang pananong.'),
  f(T.SUB_grammar_fil,'Ano ang pagkakaiba ng "at" at "o" bilang pang-ugnay?','"AT" — nagdudugtong ng mga bagay na PAREHONG totoo o nangyayari nang sabay.\nHalimbawa: "Kumain siya AT uminom ng tubig."\n"O" — nagpapahiwatig ng PAGPIPILIAN — isa sa mga bagay ang nangyayari.\nHalimbawa: "Alin ang gusto mo, kape O tsa?"\n"O KAYA" — nagpapahiwatig ng alternatibo: "Maaari kang maglakad, o kaya ay sumakay ng jeep."'),
];

// ── FILIPINO READING COMPREHENSION (14 new Pro, 9 new Sub) ────────────────────
const filReading = [
  // Pro
  f(T.PRO_reading_fil,'Pangunahing ideya ng talata: Paano ito mahahanap?','Ang PANGUNAHING IDEYA ay ang pinakamahalagang mensahe ng talata — ito ang gustong ipaabot ng may-akda.\nParaan ng paghanap:\n1. Basahin ang UNANG pangungusap — madalas doon ang paksa-pangungusap.\n2. Itanong: "Anong paksa ang tinalakay sa buong talata?"\n3. Ang tamang sagot ay dapat suportahan ng LAHAT ng pangungusap sa talata.\n4. Iwasan ang mga sagot na masyadong malawak o masyadong makitid.'),
  f(T.PRO_reading_fil,'Implikasyon at konklusyon sa Filipino na teksto','IMPLIKASYON — ang kahulugang hindi direkta at lantarang sinasabi ng may-akda, ngunit maaaring maunawaan mula sa konteksto.\nPaano sagutin: (1) Basahin ang teksto nang mabuti; (2) Tukuyin ang mga pahiwatig; (3) Isaalang-alang ang konteksto at tono; (4) Huwag magdagdag ng impormasyon na wala sa teksto.\nHalimbawa: Kung nagsabi ang may-akda na "Pumunta siya sa ospital pagkaraang magtrabaho," implikasyon: siya ay may karamdaman o napagod.'),
  f(T.PRO_reading_fil,'Paano matukoy ang layunin ng may-akda sa isang tekstong Filipino?','Uri ng layunin ng may-akda:\n1. MAGPALIWANAG — nagbibigay ng impormasyon o pagtuturo\n2. MANGHIKAYAT — nagnanais na baguhin ang pananaw o kilos ng mambabasa\n3. MAGLIBANG — nagpapasaya o nagbibigay ng kasiyahan\n4. MAGPAHAYAG — nagpapabuti ng damdamin o karanasan\nParaan: Pansinin ang uri ng wika (pormal/impormal), gamit ng mga salita (emosyonal/lohikal), at estilo ng pagsulat.'),
  f(T.PRO_reading_fil,'Paano matukoy ang tono at damdamin ng may-akda?','TONO — ang saloobin o damdamin ng may-akda na nararamdaman sa kanyang pagsulat.\nMga uri ng tono: malungkot, masaya, galit, mapagbiro, seryoso, mapanuri, maawain.\nParaan: (1) Pansinin ang mga salitang ginamit (positibo/negatibo); (2) Tingnan kung aling damdamin ang nangingibabaw; (3) Isaalang-alang ang paksa at konteksto.\nHalimbawa: Kung gumagamit ng mga salitang "mapait," "lungkot," "pighati" → malungkot na tono.'),
  f(T.PRO_reading_fil,'Paano sagutin ang mga tanong tungkol sa detalye ng talata?','Para sa mga tanong tungkol sa DETALYE (specific details):\n1. Hanapin ang eksaktong bahagi ng teksto na sumasagot sa tanong.\n2. Huwag umasa sa memorya — bumalik sa teksto.\n3. Ang tamang sagot ay direktang nakasaad sa teksto.\n4. Mga keyword sa tanong (paano, saan, sino, kailan) ay makakatulong sa paghahanap.\n5. Ang sagot sa "detalye" na tanong ay hindi nangangailangan ng interpretasyon.'),
  f(T.PRO_reading_fil,'Paano matukoy kung ang isang pahayag ay KATOTOHANAN (katunayan) o OPINYON?','KATOTOHANAN (Fact) — maaaring patunayan o bigyang-katibayan.\nHalimbawa: "Ang Pilipinas ay binubuo ng 7,641 pulo."\nOPINYON — nagpapahayag ng paniniwala, hinuha, o pagpapahalaga.\nHalimbawa: "Ang Pilipinas ay ang pinakamagandang bansa sa Asya."\nMga salitang nagpapahiwatig ng opinyon: "sa aking palagay," "tila," "marahil," "dapat," "pinakamabuti."\nMga salitang nagpapahiwatig ng katotohanan: "ayon sa datos," "ipinakita ng pananaliksik."'),
  f(T.PRO_reading_fil,'Konteksto ng salita: Paano malaman ang kahulugan ng hindi pamilyar na salita?','Mga paraan ng paggamit ng context clues:\n1. KASINGKAHULUGAN — nagbibigay ng salitang katulad: "ang matiyaga, o mapagtiis, ay tagumpay ang abutin."\n2. KASALUNGAT — nagpapakita ng kaibahan: "hindi siya mahiyain, kundi matapang."\n3. DEPINISYON — direktang nagpapaliwanag: "ang disiplina, ibig sabihin ang pagsunod sa mga patakaran..."\n4. HALIMBAWA — nagbibigay ng katulad na bagay.'),
  f(T.PRO_reading_fil,'Pagkakasunud-sunod ng mga pangyayari (sequence of events)','Mga salitang nagpapakita ng pagkakasunud-sunod:\nUNA, PANGALAWA, PANGHULI, PAGKATAPOS, BAGO, NANG, HABANG, KASABAY NITO, SA KALAUNAN, SA WAKAS.\nParaan ng pag-aayos: (1) Basahin ang buong teksto; (2) Tukuyin ang mga pangyayari; (3) Hanapin ang mga signal words para sa pagkakasunud-sunod; (4) Ayusin ayon sa tamang kronolohikal na pagkakasunud-sunod.'),
  f(T.PRO_reading_fil,'Paano sagutin ang "Alin sa mga sumusunod ang pinakamainam na pamagat?"','Ang PINAKAMAINAM NA PAMAGAT ay:\n1. Sumasalamin sa PANGUNAHING IDEYA ng buong teksto — hindi lamang isang bahagi.\n2. MAIKLI at MALINAW — hindi masyadong mahaba o masyadong malabo.\n3. NAGBIBIGAY-ZEST — hindi masyadong obiyus pero hindi rin nakalilito.\nParaan: Basahin ang buong teksto, tukuyin ang pangunahing ideya, pumili ng pinakaangkop na pamagat mula sa mga pagpipilian.'),
  f(T.PRO_reading_fil,'Paano sagutin ang "Anong uri ng teksto ito?"','URI NG TEKSTO:\n1. NAGSASALAYSAY (Narrative) — nagkukuwento ng mga pangyayari.\n2. NAGLALARAWAN (Descriptive) — nagbibigay ng masusing paglalarawan.\n3. NAGPAPALIWANAG (Expository) — nagbibigay ng impormasyon o nagpapaliwanag ng konsepto.\n4. NAGTANGGOL (Argumentative/Persuasive) — nagtatanggol ng isang pananaw.\n5. TALAKAYIN (Analytical) — nagbibigay ng malalim na pagsusuri.\nParaan: Tingnan ang layunin ng may-akda at estilo ng pagsulat.'),
  f(T.PRO_reading_fil,'Paano suriin ang isang talata para sa kabuuang kahulugan?','PROSESO NG PAG-UNAWA:\n1. BAGO BASAHIN: Tingnan ang pamagat at mga heading; hulaan ang paksa.\n2. HABANG BINABASA: Bilangin ang pangunahing ideya per talata; markahan ang mahahalagang salita.\n3. PAGKATAPOS BASAHIN: Isulat sa sariling salita ang kabuuang mensahe; sagutin ang mga tanong tungkol sa pangunahing ideya, detalye, implikasyon, at layunin ng may-akda.'),
  f(T.PRO_reading_fil,'Paano matukoy ang "pinakamainam na konklusyon" ng isang talata?','Ang PINAKAMAINAM NA KONKLUSYON:\n1. Direkta at lohikal na sumusunod mula sa mga ibinigay na impormasyon.\n2. Hindi nangangangailangan ng karagdagang impormasyon mula sa labas ng teksto.\n3. Hindi nagdadagdag ng hindi nabanggit na detalye.\n4. Nagpapaalala ng pinakamahalagang punto.\nIwasan: Mga konklusyon na: masyadong malawak, hindi suportado ng teksto, o nagpapahiwatig ng personal na opinyon ng nagtatanong.'),
  f(T.PRO_reading_fil,'Paano sagutin ang mga tanong tungkol sa "argumento" ng may-akda?','Para sa mga tanong tungkol sa ARGUMENTO:\n1. Tukuyin ang PANGUNAHING CLAIM (pahayag) ng may-akda.\n2. Tukuyin ang MGA SUPORTA (ebidensya, halimbawa, katwiran).\n3. Tingnan kung ang mga suporta ay sapat para sa claim.\n4. Isaalang-alang ang mga KONTRA-ARGUMENTO na binanggit (kung mayroon).\n5. Sagutin ang tanong batay sa nilalaman ng teksto, hindi sa personal na pananaw.'),
  f(T.PRO_reading_fil,'Paano matukoy ang target na mambabasa ng isang teksto?','Mga paraan ng pagtukoy ng TARGET NA MAMBABASA:\n1. ANTAS NG WIKA — pormal (propesyonal) o impormal (kabataan, karaniwang tao)\n2. PAKSA — anong grupo ang pinakainteresado rito?\n3. GAMIT NG TEKSTO — pahayagan, aklat-aralin, opisyal na memo, blog\n4. MGA TERMINO — teknikal (eksperto) o simple (pangkaraniwan)\nHalimbawa: Ang isang teksto na gumagamit ng maraming medikal na termino ay para sa mga manggagamot, hindi sa pangkaraniwang mambabasa.'),
  // Sub
  f(T.SUB_reading_fil,'Paano hanapin ang pangunahing ideya ng isang maikling talata?','Mga hakbang:\n1. Basahin ang buong talata nang mabagal.\n2. Tingnan ang UNANG pangungusap — madalas ito ang paksa-pangungusap.\n3. Itanong: "Ano ang pinaguusapan ng buong talata?"\n4. Ang tamang sagot ay dapat tumugma sa LAHAT ng pangungusap, hindi sa isa lang.'),
  f(T.SUB_reading_fil,'Ano ang kaibahan ng pangunahing ideya at suporta?','PANGUNAHING IDEYA — ang pinakamahalaga at pinakamalawig na mensahe ng talata.\nSUPORTANG DETALYE — mga halimbawa, ebidensya, o paliwanag na nagpapatibay ng pangunahing ideya.\nHalimbawa:\nPang. Ideya: "Mahalaga ang edukasyon sa pag-unlad."\nDetalye: "Ang mga may mataas na edukasyon ay may mas mataas na kita." (suporta)'),
  f(T.SUB_reading_fil,'Paano sagutin ang tanong: "Ano ang damdamin ng may-akda?"','Mga paraan:\n1. Pansinin ang mga salitang nagpapakita ng damdamin (masaya, malungkot, galit, etc.).\n2. Tingnan kung positibo o negatibo ang tono ng teksto.\n3. Isaalang-alang ang paksa at paraan ng pagsulat.\nHalimbawa: Kung puro positibong salita ang ginagamit tungkol sa paksa → maayos at paborableng damdamin ng may-akda.'),
  f(T.SUB_reading_fil,'Paano matukoy ang layunin ng isang maikling teksto?','Tatlong pangunahing layunin:\n1. MAGPALIWANAG — nagbibigay ng impormasyon.\n2. MANGHIKAYAT — nagnanais baguhin ang paniniwala o kilos.\n3. MAGLIBANG — nagbibigay ng kasiyahan.\nPaano matukoy: (1) Basahin ang buong teksto; (2) Itanong kung ano ang nais gawin ng may-akda sa mambabasa; (3) Pumili sa tatlong layunin na pinakaaangkop.'),
  f(T.SUB_reading_fil,'Paano gamitin ang mga pahiwatig ng konteksto para malaman ang kahulugan ng isang salita?','Mga uri ng context clue:\n1. SINONIMO — nagbibigay ng salitang katulad sa parehong pangungusap.\n2. KASALUNGAT — nagpapakita ng kaibahan.\n3. KAHULUGAN — direktang nagpapaliwanag ng salita.\n4. HALIMBAWA — nagbibigay ng katulad na sitwasyon.\nParaan: Tingnan ang mga salita at pangungusap BAGO at PAGKATAPOS ng hindi pamilyar na salita.'),
  f(T.SUB_reading_fil,'Paano sagutin ang mga tanong tungkol sa mga detalye ng tekstong Filipino?','Para sa mga tanong tungkol sa DETALYE:\n1. Hanapin ang tamang bahagi ng teksto.\n2. Huwag umasa sa memorya — bumalik at basahin muli.\n3. Ang sagot ay malapit sa verbatim sa teksto.\n4. Hanapin ang eksaktong impormasyon (pangalan, petsa, lugar, numero, atbp.)'),
  f(T.SUB_reading_fil,'Paano matukoy ang paksa ng isang maikling talata?','PAKSA (topic) ay ang nangungunang bagay, tao, o ideya na paguusapan.\nKaibahan sa pangunahing ideya: Ang PAKSA ay isang salita o parirala (hal. "edukasyon"), ang PANGUNAHING IDEYA ay isang kumpleto at tiyak na pahayag ("Ang edukasyon ay susi sa tagumpay").\nParaan: Hanapin ang salitang pinakamadalas na binabanggit o ang pinaka-central na tema.'),
  f(T.SUB_reading_fil,'Ano ang konklusyon at paano ito matutukoy?','Ang KONKLUSYON ay ang lohikal na katapusan ng argumento o talata — ang kabuuang mensahe.\nParaan ng pagtukoy: (1) Basahin ang buong teksto; (2) Itanong kung ano ang gustong sabihin ng may-akda sa kabuuan; (3) Ang konklusyon ay madalas na nasa HULING pangungusap o talata.\nMga signal words: "kaya," "samakatuwid," "dahil dito," "sa madaling salita," "sa kabuuan."'),
  f(T.SUB_reading_fil,'Paano sagutin ang tanong: "Alin sa mga sumusunod ang pinakamainam na pamagat para sa teksto?"','Ang pinakamainam na pamagat:\n1. Sumasaklaw sa BUONG paksa — hindi lamang isang bahagi.\n2. MAIKLI at MALINAW.\n3. Hindi masyadong malabo o masyadong espesipiko.\nParaan: Tukuyin muna ang pangunahing ideya ng buong teksto, pagkatapos ay pumili ng pamagat na pinaka-akma dito.'),
];

// ── FILIPINO PARAGRAPH DEVELOPMENT (14 Pro, 9 Sub) ───────────────────────────
const filPara = [
  // Pro
  f(T.PRO_para_fil,'Ano ang paksa-pangungusap (topic sentence) at saan ito matatagpuan?','Ang PAKSA-PANGUNGUSAP ay ang pangungusap na nagpapahayag ng pangunahing ideya ng talata.\nMadalas itong matatagpuan sa:\n1. SIMULA ng talata (pinaka-karaniwan)\n2. KATAPUSAN ng talata (pang-konklusyon na estilo)\n3. GITNA ng talata (bihirang mangyari)\nKatangian: Sapat na malawak upang sakupin ang buong talata ngunit sapat na tiyak upang maging pokus ng talata.'),
  f(T.PRO_para_fil,'Ano ang pagkakaisa (unity) ng talata?','PAGKAKAISA (Unity) — lahat ng pangungusap sa talata ay may kaugnayan sa pangunahing ideya (paksa-pangungusap). Walang pangungusap na "naliligaw" at hindi kaugnay sa paksa.\nParaan ng pagsuri: Basahin ang bawat pangungusap at itanong, "Sinusuportahan ba nito ang paksa-pangungusap?" Kung HINDI → ito ay nagtatanggal ng pagkakaisa.'),
  f(T.PRO_para_fil,'Ano ang pagkakaugnay (coherence) ng talata?','PAGKAKAUGNAY (Coherence) — maayos at malinaw ang daloy ng mga ideya mula sa isang pangungusap patungo sa isa pa. Ang mambabasa ay madaling susundan ang lohikal na pagkakasunud-sunod.\nMga gamit: pang-ugnay na salita (gayunpaman, dahil dito, bilang karagdagan, sa kabilang dako), pag-uulit ng mga susing salita, at paggamit ng panghalip.'),
  f(T.PRO_para_fil,'Ano ang mga uri ng transisyon na salita sa Filipino at paano gamitin ang mga ito?','Uri ng transisyon:\n1. PAGDARAGDAG: bukod dito, higit pa rito, dagdag pa rin\n2. KAIBAHAN: gayunpaman, sa kabila nito, sa kabilang dako, subalit\n3. SANHI-EPEKTO: dahil dito, bilang bunga nito, kaya naman\n4. PAGPAPALAWIG: halimbawa, sa katunayan, upang maliwanagan\n5. PAGBUBUO: sa kabuuan, sa madaling salita, samakatuwid\nGamit: Ilagay sa pagitan ng mga pangungusap o talata upang mapabuti ang daloy.'),
  f(T.PRO_para_fil,'Paano bumuo ng epektibong pangungusap na konklusyon (concluding sentence)?','Ang pangungusap na konklusyon ay:\n1. Nagbubuod ng pangunahing ideya ng talata (hindi kopya ng paksa-pangungusap)\n2. Nagbibigay ng pangkalahatang pahayag na nagtatakda ng kabuuang kahulugan\n3. Hindi nagpapakilala ng bagong impormasyon na hindi pa tinalakay\n4. Kadalasang nagsisimula sa mga salita: "Sa kabuuan," "Samakatuwid," "Kung kaya\'t," "Bilang pangwakas"'),
  f(T.PRO_para_fil,'Ano ang pagkakaiba ng talata-nagsasalaysay at talata-nagpapaliwanag?','TALATA-NAGSASALAYSAY — nagkukuwento ng mga pangyayari sa lohikal o kronolohikal na pagkakasunud-sunod. Gumagamit ng mga salitang nagpapakita ng oras (una, pagkatapos, sa wakas).\n\nTALAKA-NAGPAPALIWANAG — nagbibigay ng impormasyon, nagpapaliwanag ng konsepto, o nagturuan. Gumagamit ng mga salitang nagpapakita ng dahilan at epekto, o detalyadong paglalarawan.'),
  f(T.PRO_para_fil,'Ano ang talata-naglalarawan (descriptive paragraph)?','TALATA-NAGLALARAWAN — nagbibigay ng masining at detalyadong paglalarawan ng tao, lugar, bagay, o sitwasyon upang maging malinaw ang imahe sa isip ng mambabasa.\nGagamitin: Mga makulay na pang-uri, pigurang retorika (simili, metapora), at mga salitang nakikilinig sa pandama (paningin, pag-iingat, panlasa, amoy, pakiramdam).\nLayunin: Para maging "makita" ng mambabasa ang inilarawan.'),
  f(T.PRO_para_fil,'Ano ang talata-argumentatibo/persuasibo?','TALATA-ARGUMENTATIBO — nagtatanggol ng isang pananaw o posisyon gamit ang mga lohikal na katwiran at ebidensya.\nEstruktura: (1) Paksa-pangungusap na nagpapahayag ng pananaw; (2) Mga suportang detalye (dahilan, ebidensya, halimbawa); (3) Konklusyon na nagpapatibay ng pananaw.\nLayunin: Kumbinsihin ang mambabasa na tanggapin ang pananaw ng may-akda.'),
  f(T.PRO_para_fil,'Paano sumulat ng mabuting talata sa Filipino? (General guidelines)','MGA PAMANTAYAN NG MABUTING TALATA:\n1. Malinaw at tiyak na paksa-pangungusap\n2. Sapat na mga suportang pangungusap (detalye, halimbawa, katibayan)\n3. Pagkakaisa (lahat ng pangungusap ay may kaugnayan sa paksa)\n4. Pagkakaugnay (maayos ang daloy; gumagamit ng transisyon)\n5. Tamang pagwawakas (konklusyon o transisyon sa susunod na talata)\n6. Wastong gamit ng wika (gramatika, baybay, bantas)'),
  f(T.PRO_para_fil,'Ano ang pagkakaiba ng "paksa" at "pangunahing ideya" ng talata?','PAKSA — ang pangunahing bagay, tao, lugar, o ideya na pinaguusapan sa talata.\nHalimbawa ng paksa: "Edukasyon sa Pilipinas"\n\nPANGUNAHING IDEYA — ang partikular na punto o argumento tungkol sa paksa.\nHalimbawa ng pangunahing ideya: "Ang edukasyon sa Pilipinas ay nangangailangan ng mas malaking badyet."\n\nAng pangunahing ideya ay mas tiyak at kumpleto kaysa sa paksa.'),
  f(T.PRO_para_fil,'Paano mapabuti ang pagkakaugnay ng mga talata sa isang mas mahabang akda?','Mga pamamaraan para sa inter-paragraph coherence:\n1. TRANSISYON NA PANGUNGUSAP sa simula ng bawat bagong talata na nagdudugtong sa nakaraan.\n2. PAG-UULIT NG SUSING SALITA — gamitin muli ang mga mahalagang salita mula sa nakaraang talata.\n3. PANGHALIP — "ito," "sila," "ang mga ito" na tumutukoy sa nakaraang paksa.\n4. PAGBUBUOD — maikling pagbubuod ng nakaraan bago lumipat sa susunod na paksa.'),
  f(T.PRO_para_fil,'Ano ang "sentence outline" at "topic outline" sa paghahanda ng pagsulat?','TOPIC OUTLINE — ginagamit ang mga parirala o salita lamang (hindi kumpleto).\nHalimbawa:\nI. Kahulugan ng edukasyon\n   A. Pormal\n   B. Di-pormal\n\nSENTENCE OUTLINE — bawat aytem ay isang kumpleto at ganap na pangungusap.\nHalimbawa:\nI. Ang edukasyon ay ang proseso ng pagkatuto at pag-unlad ng tao.\n   A. Ang pormal na edukasyon ay nagaganap sa paaralan.'),
  f(T.PRO_para_fil,'Ano ang "pigurang retorika" at bakit ginagamit ito sa pagsulat?','PIGURANG RETORIKA ay mga espesyal na paraan ng paggamit ng wika upang mas mabisa at mas matandaan ang mensahe.\nMga halimbawa:\n1. SIMILI — paghahambing gamit ang "tulad ng" o "para ng": "Mabilis siyang tumakbo para ng hangin."\n2. METAPORA — direktang paghahambing: "Ang karunungan ay ilaw ng buhay."\n3. PERSONIPIKASYON — pagbibigay ng katangiang pantao sa hindi-tao: "Ang alon ay humahagod sa dalampasigan."\n4. HYPERBOLE — pagmamalabis: "Naghintay ako ng isang taon sa pila."'),
  f(T.PRO_para_fil,'Paano mapabuti ang pagkakaugnay sa loob ng isang talata?','Mga pamamaraan:\n1. PANG-UGNAY NA SALITA: kaya naman, bukod dito, higit pa rito, samakatuwid, halimbawa.\n2. PANGHALIP: siya, sila, ito, ang kanyang, ang mga ito → tumutukoy sa nabanggit na paksa.\n3. PAG-UULIT: Ulitin ang susing salita o konsepto.\n4. LOHIKAL NA PAGKAKASUNUD-SUNOD: kronolohikal, deduktibo (pangkalahatan → partikular), induktibo (partikular → pangkalahatan).'),
  // Sub
  f(T.SUB_para_fil,'Ano ang paksa-pangungusap (topic sentence)?','Ang PAKSA-PANGUNGUSAP ay ang pinakamahalagang pangungusap ng talata — nagpapahayag ng pangunahing ideya.\nMadalas nasa SIMULA ng talata.\nKaraniwan: "Ang ___ ay ___." o "Mahalaga ang ___ dahil ___."'),
  f(T.SUB_para_fil,'Ano ang kaibahan ng paksa at pangunahing ideya?','PAKSA — ang bagay o tao na paguusapan (isang salita o parirala).\nPangunahing Ideya — ang kompletong pahayag tungkol sa paksa.\nHalimbawa: Paksa: "Tubig." Pangunahing Ideya: "Ang tubig ay mahalaga para sa buhay ng bawat nilalang."'),
  f(T.SUB_para_fil,'Bakit kailangan ng mga suportang pangungusap sa isang talata?','Ang mga SUPORTANG PANGUNGUSAP ay nagbibigay ng mga detalye, halimbawa, at katwiran na nagpapatibay ng paksa-pangungusap.\nBawat suportang pangungusap ay dapat direktang may kaugnayan sa pangunahing ideya.\nKung walang suporta: ang talata ay magiging walang saysay at hindi kapani-paniwala.'),
  f(T.SUB_para_fil,'Ano ang mga salitang nagpapakita ng pagkakaugnay ng mga ideya?','TRANSISYONAL NA SALITA:\nPAGDADAGDAG: bukod pa rito, dagdag pa, pati na rin\nKAIBAHAN: ngunit, subalit, gayunman, sa kabilang dako\nSANHI-EPEKTO: kaya, dahil dito, bilang resulta\nPAGBUBUO: sa kabuuan, sa madaling salita, samakatuwid\nPAGPAPALAWIG: halimbawa, sa katunayan, bilang karagdagan'),
  f(T.SUB_para_fil,'Paano malalaman kung may pagkakaisa ang isang talata?','Ang talata ay may PAGKAKAISA kung: ang bawat pangungusap ay nagpapalawig at nagpapatibay ng paksa-pangungusap.\nParaan ng pagsuri: Basahin ang bawat pangungusap at itanong: "Kaugnay ba ito ng pangunahing ideya?" Kung may pangungusap na HINDI kaugnay → wala itong pagkakaisa.'),
  f(T.SUB_para_fil,'Ano ang ginagawa ng konklusyon sa katapusan ng talata?','Ang PANGUNGUSAP NG KONKLUSYON ay nagbubuod ng pangunahing ideya ng talata. Ito ay nagbibigay ng pagtatapos at nagpapalakas ng mensahe ng may-akda.\nHalimbawa: "Kaya naman, malinaw na ang edukasyon ay susi sa tagumpay ng bawat Pilipino."'),
  f(T.SUB_para_fil,'Ano ang pagkakaiba ng talata-nagsasalaysay at talata-nagpapaliwanag?','NAGSASALAYSAY — nagkukuwento ng mga pangyayari; may simula, gitna, at katapusan.\nNAGPAPALIWANAG — nagbibigay ng impormasyon o nagpapaliwanag ng konsepto; walang kwentong istraktura.'),
  f(T.SUB_para_fil,'Ano ang ibig sabihin ng "maiksi at malinaw na pagsulat"?','Ang maiksi at malinaw na pagsulat ay nangangahulugang:\n1. Gamitin ang pinakamaikling paraan ng pagpapahayag ng isang ideya.\n2. Iwasan ang mga salitang walang silbi o paulit-ulit.\n3. Maging tiyak at kongkreto — iwasan ang malabong pahayag.\n4. Gumamit ng simpleng salita kapag posible.'),
  f(T.SUB_para_fil,'Paano gumawa ng outline bago sumulat ng talata?','Mga hakbang:\n1. Tukuyin ang PANGUNAHING IDEYA (paksa-pangungusap).\n2. Ilista ang 3-5 SUPORTANG PUNTO (mga detalye, halimbawa).\n3. Ayusin ang mga punto sa lohikal na pagkakasunud-sunod.\n4. Isulat ang talata batay sa outline.\nHalimbawa ng outline:\nPangunahing Ideya: "Mahalaga ang tubig sa buhay."\nA. Ginagamit sa pag-inom B. Ginagamit sa pagluluto C. Ginagamit sa kalinisan'),
];

// ── PARAGRAPH ORGANIZATION (15 Pro, 14 Sub) ────────────────────────────────────
const paraOrg = [
  // Pro
  f(T.PRO_para_org,'What is the deductive pattern of paragraph organization?',
    'DEDUCTIVE pattern: General → Specific. Start with the topic sentence (main idea), then support it with specific details, examples, or evidence.\nMost common pattern in formal writing.\nExample: "Regular exercise improves health. [topic sentence] It strengthens the heart, builds muscle, and reduces stress. Studies show that 30 minutes of daily exercise reduces heart disease risk by 35%. [details]"'),
  f(T.PRO_para_org,'What is the inductive pattern of paragraph organization?',
    'INDUCTIVE pattern: Specific → General. Begin with specific details, examples, or facts, then arrive at the main idea/conclusion at the end.\nUseful for building suspense or persuasion.\nExample: "Heart disease rates drop among those who exercise. Blood pressure normalizes. Muscle mass increases. Studies confirm it. [details] → Therefore, regular exercise is essential for good health. [conclusion/topic sentence at end]"'),
  f(T.PRO_para_org,'What are "bridge sentences" in multi-paragraph composition?',
    'BRIDGE SENTENCES (transitional sentences) connect the end of one paragraph to the beginning of the next. They ensure smooth reading flow.\nTechniques: (1) Echo a key word from the previous paragraph; (2) Use a transitional phrase; (3) Reference the previous paragraph\'s main idea.\nExample: "Having discussed the causes of poverty [recap], we now turn to the most effective solutions. [lead-in to next paragraph]"'),
  f(T.PRO_para_org,'What are the 5 types of supporting details in a paragraph?',
    '1. FACTS — verifiable statements, statistics\n2. EXAMPLES — specific instances illustrating the main idea\n3. REASONS — explanations of why the main idea is true\n4. DESCRIPTIONS — sensory or detailed portrayals\n5. QUOTATIONS/TESTIMONY — words from experts or authorities\nTip: A strong paragraph uses multiple types of support, not just one.'),
  f(T.PRO_para_org,'What is the Compare-Contrast paragraph pattern?',
    'COMPARE-CONTRAST: discusses similarities (compare) and differences (contrast) between two or more subjects.\nTwo formats:\n1. POINT-BY-POINT: Discuss A and B alternately for each characteristic. (A-B, A-B, A-B)\n2. BLOCK: Discuss all of A first, then all of B. (AAA, BBB)\nSignal words: similarly, likewise, on the other hand, however, in contrast, while, whereas.'),
  f(T.PRO_para_org,'What is the Cause-Effect paragraph pattern?',
    'CAUSE-EFFECT pattern: explains why something happened (causes) and/or what resulted from it (effects).\nVariants: (1) SINGLE CAUSE → MULTIPLE EFFECTS; (2) MULTIPLE CAUSES → SINGLE EFFECT; (3) CAUSE-EFFECT CHAIN.\nSignal words (cause): because, since, due to, as a result of.\nSignal words (effect): therefore, consequently, thus, hence, as a result, led to.'),
  f(T.PRO_para_org,'What is the Problem-Solution paragraph pattern?',
    'PROBLEM-SOLUTION: presents a problem and proposes one or more solutions.\nStructure: (1) Identify and describe the problem; (2) Analyze the causes; (3) Propose solution(s); (4) Evaluate the solution.\nSignal words: the problem is, one solution is, to resolve this, this can be addressed by, the best approach is.'),
  f(T.PRO_para_org,'What is the Classification paragraph pattern?',
    'CLASSIFICATION: divides a subject into categories based on a shared characteristic.\nRules for valid classification: (1) Categories must be EXHAUSTIVE (cover all members); (2) Categories must be MUTUALLY EXCLUSIVE (no overlap); (3) Use ONE consistent basis for classification.\nExample: "Students can be classified by study habits: visual learners, auditory learners, and kinesthetic learners."'),
  f(T.PRO_para_org,'What is the Process/Sequential paragraph pattern?',
    'PROCESS/SEQUENTIAL: explains how to do something or how something happens, step by step.\nTypes: (1) HOW-TO (instructions): readers can follow to replicate the process; (2) HOW-IT-WORKS (explanation): describes a process for understanding.\nSignal words: first, second, then, next, after, finally, subsequently, at this point, once, when.\nKey: Steps must be in the CORRECT ORDER.'),
  f(T.PRO_para_org,'What is the Spatial/Descriptive paragraph organization?',
    'SPATIAL pattern: describes a place or object by moving systematically through space (top-to-bottom, left-to-right, near-to-far, outside-to-inside).\nUsed in: descriptive essays, travel writing, reports about facilities.\nSignal words: in the center, to the left, behind, above, next to, in the foreground, further out.\nTip: Establish a consistent viewpoint and direction.'),
  f(T.PRO_para_org,'What makes a paragraph "well-developed"?',
    'A WELL-DEVELOPED paragraph:\n1. Has a clear, focused topic sentence\n2. Provides SUFFICIENT support (not just one example)\n3. Uses VARIED types of support (facts, examples, reasons)\n4. ELABORATES on each supporting point (doesn\'t just list)\n5. Avoids padding (unnecessary filler) or underdevelopment (too brief)\nTest: Would a reader who doesn\'t know the subject understand the paragraph fully? If not, it needs more development.'),
  f(T.PRO_para_org,'What is a "paragraph hook" and why is it used?',
    'A HOOK is the opening of an introductory paragraph designed to grab the reader\'s attention.\nTypes of hooks:\n1. STARTLING STATISTIC: "One in three Filipinos faces food insecurity."\n2. THOUGHT-PROVOKING QUESTION: "What would you do with an extra 5 hours a day?"\n3. ANECDOTE: Brief relevant story.\n4. QUOTATION: From an authority on the topic.\n5. BOLD STATEMENT: A provocative or surprising claim.'),
  f(T.PRO_para_org,'What is a thesis statement in a multi-paragraph essay?',
    'The THESIS STATEMENT is the central claim of an entire essay (not just one paragraph). It appears in the introduction and tells readers: (1) the topic, (2) your position/main point, and (3) the key supporting reasons (optional).\nExample: "The Philippines must strengthen its anti-corruption laws [topic], expand citizen oversight mechanisms [reason 1], and impose stricter penalties [reason 2] to reduce graft."\nKey: Specific and debatable — not just a fact.'),
  f(T.PRO_para_org,'What is paragraph coherence and how is it achieved?',
    'COHERENCE: ideas flow smoothly so readers can follow without confusion.\nAchieved through:\n1. LOGICAL ORDER (chronological, order of importance, spatial)\n2. TRANSITIONAL WORDS (furthermore, however, as a result)\n3. PRONOUN REFERENCE (referring to previously named nouns)\n4. REPETITION of key words/concepts\n5. PARALLEL STRUCTURE (using the same grammatical form for similar ideas)'),
  f(T.PRO_para_org,'What is the difference between summary and paraphrase?',
    'SUMMARY: condenses the original material into a much shorter version, capturing only the main ideas.\nPARAPHRASE: restates the original in different words without changing the meaning; roughly the same length.\nBoth require: attribution to the source; do NOT copy the original word-for-word.\nWhen to use: Summary for long texts; paraphrase for specific key passages. Both avoid plagiarism in academic writing.'),
  // Sub
  f(T.SUB_para_org,'What is the topic sentence and where is it usually found?',
    'The TOPIC SENTENCE states the MAIN IDEA of a paragraph. It is usually the FIRST sentence.\nExample: "Exercise has many benefits for the human body." (topic sentence)\n[Followed by: details about specific benefits]\nTip: If the topic sentence is at the end, it acts as a conclusion — usually in inductive paragraphs.'),
  f(T.SUB_para_org,'What are supporting sentences in a paragraph?',
    'SUPPORTING SENTENCES provide details, examples, and reasons that develop and prove the topic sentence.\nTypes: facts, examples, statistics, descriptions, expert opinions.\nExample: Topic: "Exercise is beneficial."\nSupport: "A 2023 study showed daily walking reduces heart disease risk by 30%."\nRule: Every supporting sentence must relate directly to the topic sentence.'),
  f(T.SUB_para_org,'What is a concluding sentence and when is it needed?',
    'A CONCLUDING SENTENCE wraps up the paragraph by restating the main idea in different words or summarizing the key points.\nUsually the LAST sentence of the paragraph.\nSignal words: "In summary," "Therefore," "In conclusion," "Clearly," "Thus."\nNot always required — short paragraphs in informal writing may not need one.'),
  f(T.SUB_para_org,'What are common transition words and their uses?',
    'ADDITION: also, furthermore, in addition, moreover\nCONTRAST: but, however, on the other hand, although\nCAUSE: because, since, due to\nEFFECT: therefore, as a result, consequently\nEXAMPLE: for example, for instance, such as\nSEQUENCE: first, next, then, finally\nCONCLUSION: in summary, in conclusion, overall'),
  f(T.SUB_para_org,'What is "unity" in a paragraph?',
    'UNITY: Every sentence in the paragraph relates to the topic sentence. No sentence goes off-topic.\nTest for unity: Read each sentence and ask "Does this support the topic sentence?" If one sentence doesn\'t → unity is broken.\nExample error: Paragraph about exercise benefits includes a sentence about diet → off-topic; breaks unity.'),
  f(T.SUB_para_org,'How do you identify the main idea of a paragraph if the topic sentence is not at the beginning?',
    'Strategy:\n1. Read the entire paragraph.\n2. Ask: "What is the central message that ALL sentences support?"\n3. Check the LAST sentence — the main idea may be there (inductive pattern).\n4. Eliminate answer choices that are too broad, too narrow, or only cover one part of the paragraph.'),
  f(T.SUB_para_org,'What are the 3 main patterns of paragraph organization?',
    '1. CHRONOLOGICAL: events in time order (first, then, finally)\n2. SPATIAL: describing locations (left to right, top to bottom)\n3. ORDER OF IMPORTANCE: from least to most important, or vice versa\n4. CAUSE-EFFECT: why something happened and what resulted\n5. COMPARE-CONTRAST: similarities and differences'),
  f(T.SUB_para_org,'What is the difference between a fact and an opinion in a paragraph?',
    'FACT: Objectively verifiable — can be proven true or false.\n"The Philippines has 7,641 islands."\nOPINION: Subjective — a belief, judgment, or interpretation.\n"The Philippines is the most beautiful country in the world."\nTip for CSE: Opinions often use words like: should, best, worst, I think, I believe, probably, seems.'),
  f(T.SUB_para_org,'What does it mean for a paragraph to be "well-organized"?',
    'A well-organized paragraph:\n1. Starts with a clear topic sentence\n2. Develops the main idea with supporting details in a logical order\n3. Uses transitions to connect ideas smoothly\n4. Ends with a clear concluding thought\nDisorganized paragraph: ideas appear randomly with no clear progression from one to the next.'),
  f(T.SUB_para_org,'What is the process/sequential pattern and when is it used?',
    'PROCESS/SEQUENTIAL pattern: lists steps in the correct order to explain HOW to do something or HOW something works.\nUsed in: instructions, recipes, explanations of procedures.\nSignal words: first, second, third, then, next, after that, finally.\nKey rule: Steps must be in the CORRECT sequence — changing the order would make the process fail.'),
  f(T.SUB_para_org,'What is the compare-contrast pattern?',
    'COMPARE-CONTRAST: discusses similarities (compare) and differences (contrast) between two subjects.\nSignal words: similarly, likewise (compare); however, in contrast, on the other hand, while (contrast).\nExample: "Both CSE Professional and Sub-Professional require Verbal Ability [similarity], but the Professional level includes Analytical Ability which the Sub-Professional replaces with Clerical Ability [difference]."'),
  f(T.SUB_para_org,'How do you fix a paragraph with poor coherence?',
    'To improve coherence:\n1. Add TRANSITION WORDS between sentences (furthermore, however, therefore).\n2. Use PRONOUN REFERENCES (he, she, it, they) to avoid repeating nouns.\n3. Repeat KEY WORDS to maintain focus.\n4. Arrange sentences in a LOGICAL ORDER (time, importance, space).\nPoor coherence example: ideas appear randomly without flow. Good coherence: each sentence leads naturally to the next.'),
  f(T.SUB_para_org,'What is the problem-solution paragraph pattern?',
    'PROBLEM-SOLUTION: presents a problem, then proposes one or more solutions.\nStructure:\n1. Identify the problem\n2. Describe its impact\n3. Propose solution(s)\n4. Explain how it solves the problem\nSignal words: the problem is..., one solution is..., this can be resolved by..., to address this issue...'),
  f(T.SUB_para_org,'What is the cause-effect paragraph pattern?',
    'CAUSE-EFFECT: explains why something happened (causes) and/or what resulted (effects).\nVariants: Single cause → multiple effects; Multiple causes → single effect.\nSignal words — Cause: because, since, due to, as a result of.\nSignal words — Effect: therefore, consequently, thus, hence, as a result, led to.'),
];

// ── SPELLING (26 Sub) ─────────────────────────────────────────────────────────
const spelling = [
  f(T.SUB_spelling,'Correct the spelling: "accomodate"','ACCOMMODATE (double C, double M). "The new policy will ACCOMMODATE all employees." Memory: One collar, two measures. (1 C, 2 M)'),
  f(T.SUB_spelling,'Correct the spelling: "goverment"','GOVERNMENT (do not drop the N). "The GOVERNMENT approved the new law." Tip: "govern" + "ment" — keep all letters of "govern."'),
  f(T.SUB_spelling,'Correct the spelling: "occurence"','OCCURRENCE (double C, double R). "The OCCURRENCE of such events is rare." Memory: CC then RR — like a train going "cc-rr."'),
  f(T.SUB_spelling,'Correct the spelling: "supercede"','SUPERSEDE (ends in -sede, not -cede). "The new regulation will SUPERSEDE all previous ones." Only one word ends in "-sede": supersede. Most "-sede"-sound words end in "-cede" (precede, concede) or "-ceed" (succeed, proceed).'),
  f(T.SUB_spelling,'Correct the spelling: "recieve"','RECEIVE (i before e EXCEPT after c). "Please RECEIVE the document at the front desk." Rule: c → then e before i: re-CE-ive.'),
  f(T.SUB_spelling,'Correct the spelling: "writting"','WRITING (single T). "She is WRITING the report." Tip: write → writing (drop the final "e," do not double the "t" since "write" has a silent e and the vowel before T is a long vowel).'),
  f(T.SUB_spelling,'Correct the spelling: "definately"','DEFINITELY (no "ate" — it\'s "ite"). "I will DEFINITELY attend the meeting." Tip: definITE + ly = definitely. Or: de-fin-ite-ly.'),
  f(T.SUB_spelling,'Correct the spelling: "neccessary"','NECESSARY (one C, two S). "It is NECESSARY to submit the form." Memory: "one Collar, two Socks" = 1C, 2S.'),
  f(T.SUB_spelling,'Correct the spelling: "priviledge"','PRIVILEGE (no D). "It is a PRIVILEGE to serve the public." Tip: priv-i-lege. There is no "d" anywhere.'),
  f(T.SUB_spelling,'Correct the spelling: "harrassment"','HARASSMENT (single R). "The company prohibits workplace HARASSMENT." Tip: "hara" + "ssment." Only one R, double S.'),
  f(T.SUB_spelling,'Correct the spelling: "independant"','INDEPENDENT (ends in -ent, not -ant). "The Philippines is an INDEPENDENT nation." Memory: independENT → the ending rhymes with "pent" or "tent."'),
  f(T.SUB_spelling,'Correct the spelling: "existance"','EXISTENCE (ends in -ence, not -ance). "The EXISTENCE of the law was confirmed." Tip: exist + ENCE. When in doubt, -ence is more common with verbs ending in soft sounds.'),
  f(T.SUB_spelling,'Correct the spelling: "commitee"','COMMITTEE (double M, double T, double E). "The COMMITTEE will meet tomorrow." Memory: Three pairs: mm-tt-ee.'),
  f(T.SUB_spelling,'Correct the spelling: "mispelled" / "mispell"','MISSPELL / MISSPELLED (double S). "Do not MISSPELL your name on the form." Tip: mis + spell → two S\'s meet. Also: misspelling.'),
  f(T.SUB_spelling,'Homophone pair: "principal" vs. "principle"','PRINCIPAL — the head of a school; main; chief; a sum of money. "The school PRINCIPAL called a meeting."\nPRINCIPLE — a fundamental rule or belief. "Integrity is a core PRINCIPLE of civil service."\nMemory: PrinciPAL = your PAL (person). PrincipLE = a ruLE.'),
  f(T.SUB_spelling,'Homophone pair: "complement" vs. "compliment"','COMPLEMENT — something that completes or goes well with something else (verb or noun). "The red tie COMPLEMENTS his suit."\nCOMPLIMENT — an expression of praise (verb or noun). "She gave him a COMPLIMENT on his work."\nMemory: complEment = complEte. complIment = I like.'),
  f(T.SUB_spelling,'Homophone pair: "stationary" vs. "stationery"','STATIONARY — not moving; standing still. "The bicycle is STATIONARY."\nSTATIONERY — writing materials (paper, envelopes, pens). "Order office STATIONERY from the supply room."\nMemory: stationERY = papER (both end in -er). stationARY = stAy (both have A in same position).'),
  f(T.SUB_spelling,'Homophone pair: "capital" vs. "capitol"','CAPITAL — uppercase letter; chief city; money/wealth; punishable by death. "Manila is the CAPITAL of the Philippines." / "Write in CAPITAL letters."\nCAPITOL — the building where a legislature meets. "The Philippine Congress meets in a CAPITOL."\nMemory: capitOL = bOLd building (the O is in the word for the building).'),
  f(T.SUB_spelling,'Homophone pair: "advice" vs. "advise"','ADVICE (noun) — a recommendation or suggestion. "I need your ADVICE on this matter."\nADVISE (verb) — to give advice. "I ADVISE you to read the contract carefully."\nMemory: advICE = a nOUN (both have nouns: ice, noun). advISE = a VERB (both end in similar sounds: -ise, verb forms).'),
  f(T.SUB_spelling,'Spelling rule: when to double the final consonant before -ing or -ed','Double the final consonant when: (1) word ends in consonant-vowel-consonant (CVC); AND (2) the word has only one syllable or stress is on the last syllable.\nExamples: run → running (CVC, 1 syllable). begin → beginning (CVC, stress on last). travel → traveling (NOT doubled — stress on 1st syllable).\nDo NOT double: words ending in two consonants (jump→jumping), two vowels (read→reading), or vowel + C + silent e (make→making).'),
  f(T.SUB_spelling,'Spelling rule: dropping the silent "e" before a suffix','Drop the silent E before a suffix beginning with a VOWEL.\nExamples: write → writing (drop e + -ing). hope → hoping. drive → driving.\nKEEP the silent E before a suffix beginning with a CONSONANT.\nExamples: hope → hopeful (keep e + -ful). care → careless. like → likely.\nExceptions: true → truly, argue → argument (e dropped before consonant).'),
  f(T.SUB_spelling,'Commonly misspelled Filipino government terms (Part 1)','Correct spellings:\n• BUREAU (not "buro") — Bureau of Internal Revenue\n• LIAISON (not "liasion") — person who coordinates\n• CERTIFICATE (not "sertificate") — document\n• MEMORANDUM (not "memorendum") — official memo\n• MUNICIPAL (not "munisipyal") — relating to municipality'),
  f(T.SUB_spelling,'Commonly misspelled Filipino government terms (Part 2)','Correct spellings:\n• CONSCIENTIOUS (not "consientious") — very careful\n• CONSCIENTIOUSLY — conscientious + ly\n• EFFICIENT (not "eficient") — productive with minimal waste\n• ELIGIBLE (not "elligible") — qualified\n• SIMULTANEOUS (not "simultaneuos") — happening at the same time'),
  f(T.SUB_spelling,'Compound words: hyphenated, open, or closed?','CLOSED (one word): notebook, bookshelf, classroom, workplace, furthermore.\nHYPHENATED: well-known, long-term, up-to-date, co-worker, non-profit, follow-up.\nOPEN (two words): high school, civil service, post office, tax return, real estate.\nGeneral rules: (1) Compound modifiers before a noun are usually hyphenated (well-known author). (2) After "be" verb, often not hyphenated (he is well known).'),
  f(T.SUB_spelling,'Correct the spelling: "seperate"','SEPARATE (e-a-r-a-t-e). "Please SEPARATE the documents by category."\nMemory: "separ-ATE" — there\'s a "par" in separate. Or: there is "a rat" in separate: sep-A-RAT-e.'),
  f(T.SUB_spelling,'Correct the spelling: "bussiness" / "busines"','BUSINESS (double S, one I). "The BUSINESS meeting is at 9 AM." Tip: busy + ness → but changes to business. Or: busi-NESS = busin-ess (ends in double -ss).'),
];

const allCards = [...filVocab, ...filGrammar, ...filReading, ...filPara, ...paraOrg, ...spelling];
console.log(`\nBatch D: ${allCards.length} total cards`);

const byTopic = {};
for (const card of allCards) {
  if (!byTopic[card.topic_id]) byTopic[card.topic_id] = [];
  byTopic[card.topic_id].push(card);
}

let totalInserted = 0, totalSkipped = 0;
for (const [topicId, cards] of Object.entries(byTopic)) {
  const { data: ex } = await sb.from('flashcards').select('front').eq('topic_id', topicId).limit(2000);
  const existing = new Set((ex||[]).map(r => r.front));
  const newCards = cards.filter(c => !existing.has(c.front));
  const skipped = cards.length - newCards.length;
  if (newCards.length === 0) { console.log(`  Skip all (${skipped} dupes) for ${topicId.slice(0,8)}`); continue; }
  const { error } = await sb.from('flashcards').insert(newCards);
  if (error) { console.error(`  ERROR for ${topicId.slice(0,8)}: ${error.message}`); continue; }
  totalInserted += newCards.length;
  totalSkipped += skipped;
  console.log(`  ✓ +${newCards.length} (skipped ${skipped}) → ${topicId.slice(0,8)}`);
}

const { count } = await sb.from('flashcards').select('*',{count:'exact',head:true});
console.log(`\n✅ Batch D done. Inserted: ${totalInserted}, Skipped: ${totalSkipped}`);
console.log(`📊 Total flashcards: ${count}`);
